### ISSUE TITLE
Note for Better Vampires no longer valid past version 7.2

### ISSUE THREAD

**Issue by inire** [loot/skyrim#118]
http://www.nexusmods.com/skyrim/mods/9717/?

Better vampires has a "no clean" note to not remove ITM's.

version 7.2 does not have ITM's or UDRs or ITPO's.

**Comment by Freso** [comment]
Does LOOT properly detect Better Vampires' version?

**Comment by inire** [comment]
the CRC's are different for the files, but I do not know if it is being detected. I am guessing that there needs to be a diff that gives a CRC listing of what is and is not clean?

Version 6.31 and onward does NOT have the ITM. 

Version 6.31
E651D755 - Better Vampires.esp CRC32
A4402B3C - Better Vampires ML.esp CRC32
F4AE07F0 - Better Vampires - No DawnGuard.esp CRC32
96A34871- Better Vampires ML - No DawnGuard.esp CRC32

I went back through some of the archives of the files from better vampires and found that the last file that actually had ITM's had this cleaning report.

Version 6.0. 

LOOT Masterlist Entry
- name: 'Better Vampires.esp'
  dirty:
  - crc: 0x330cf722
    util: *dirtyUtil
    itm: 1

BOSS Masterlist Entry
Better Vampires.esp
  IF CHECKSUM("Better Vampires.esp", 330CF722) DIRTY: 1 ITM, 0 UDR records. Needs TES5Edit cleaning: "http://cs.elderscrolls.com/index.php?title=TES4Edit_Cleaning_Guide"

Version 6.2

LOOT Masterlist Entry
- name: 'Better Vampires.esp'
  dirty:
  - crc: 0xda620f2f
    util: *dirtyUtil
    itm: 1

BOSS Masterlist Entry
Better Vampires.esp
  IF CHECKSUM("Better Vampires.esp", DA620F2F) DIRTY: 1 ITM, 0 UDR records. Needs TES5Edit cleaning: "http://cs.elderscrolls.com/index.php?title=TES4Edit_Cleaning_Guide"

**Comment by Ortham** [comment]
v6.31's E651D755 doesn't match the masterlist's 330cf722, so the dirty message won't get displayed for the v6.31 plugin, so I don't think there's a problem.

**Comment by Freso** [comment]
```
  - name: 'Better Vampires DG.esp'
    msg: [ *obsolete ]
  - name: 'Better Vampires.esp'
    msg: [ *doNotClean ]
  - name: 'Better Vampires ML.esp'
    inc:
      - 'Better Vampires.esp'
      - 'Better Vampires DG.esp'
    msg: [ *doNotClean ]
  - name: 'Better Vampires - No DawnGuard.esp'
    inc:
      - 'Better Vampires.esp'
      - 'Better Vampires DG.esp'
      - 'Better Vampires ML.esp'
    msg:
      - type: warn
        content:
          - lang: en
            str: 'You need the Dawnguard version of better vampires to work as intended with dawnguard.'
          - lang: ru
            str: 'Вам нужна Dawnguard-версия better vampires для правильной работы с DLC Dawnguard.'
          - lang: es
            str: 'You need the Dawnguard version of better vampires to work as intended with dawnguard.'
        condition: 'active("Dawnguard.esm")'
      - *doNotClean
  - name: 'Better Vampires ML - No DawnGuard.esp'
    inc:
      - 'Better Vampires.esp'
      - 'Better Vampires DG.esp'
      - 'Better Vampires ML.esp'
      - 'Better Vampires - No DawnGuard.esp'
    msg:
      - type: warn
        content:
          - lang: en
            str: 'You need the Dawnguard version of better vampires to work as intended with dawnguard.'
          - lang: ru
            str: 'Вам нужна Dawnguard-версия better vampires для правильной работы с DLC Dawnguard.'
          - lang: es
            str: 'You need the Dawnguard version of better vampires to work as intended with dawnguard.'
        condition: 'active("Dawnguard.esm")'
      - *doNotClean
```

Seems to be our current entries. They don't have `dirty` records, but they do have `*doNotClean` references, which I guess are the ones @inire is arguing should be removed(?). My thought was to encapsulate them in a version check, but that's only doable if the ESP files actually have a version in their description which LOOT can pick up.
