### ISSUE TITLE
FoxMerged condition is partially wrong

### ISSUE THREAD

**Issue by starkgate** [loot/skyrim#122]
The following condition is not entirely correct :

```
 - name: 'fox\d\d? Armor\.esp'
    msg:
      - type: warn
        content:
          - lang: en
            str: 'Delete. Already included in FoxMerged.esp.'
          - lang: ru
            str: 'Удалите. Уже включено в FoxMerged.esp.'
          - lang: es
            str: 'Borrar. Esta incluido en FoxMerged.esp.'
condition: 'file("FoxMerged.esp")'
```

fox51, 52, 53 Armor.esp are _not_ included in the FoxMerged.esp. The condition is only true up to "fox50 Armor.esp", as of "FoxMerged 2.6".
