### ISSUE TITLE
Userlist with possibly relevant data to merge into the masterlist

### ISSUE THREAD

**Issue by Freso** [loot/skyrim#142]
@LordOfLA gave me his userlist for potential adoption, or partial adoption, into the masterlist. However, since I haven't touched Skyrim in year and as such is quite out of the loop on the various mods etc., I don't feel comfortably going over his list and figuring out what should get added to the masterlist and what not, but I volunteered to still post it here in case one of the more active Skyrim masterlist maintainers would look it over and maybe pick out some of his entries for inclusion.

Edit: @LordOfLA separated out some groups of mods/plugins and then made a new userlist dump with those specifics weeded out:

### ELE

```yaml
plugins:
  - name: 'ELE_S_Lite.esp'
    global_priority: 75
  - name: 'ELE_DG_Lite.esp'
    after:
      - 'ELE_S_Lite'
  - name: 'ELE_HF_Lite.esp'
    after:
      - 'ELE_S_Lite'
      - 'ELE_DG_Lite'
  - name: 'ELE_DB_Lite.esp '
    after:
      - 'ELE_S_Lite'
      - 'ELE_DG_Lite'
      - 'ELE_HF_Lite'
  - name: 'ELE_S_DG_DB_Lite.esp'
    global_priority: 75
  - name: 'ELE_Wt_Lite.esp'
    after:
      - 'ELE_S_Lite'
      - 'ELE_DG_Lite'
      - 'ELE_HF_Lite'
      - 'ELE_DB_Lite'
      - 'ELE_S_DG_DB_Lite.esp'
  - name: 'ELE_Fs_Lite.esp  '
    after:
      - 'ELE_S_Lite'
      - 'ELE_DG_Lite'
      - 'ELE_HF_Lite'
      - 'ELE_DB_Lite'
      - 'ELE_Wt_Lite'
      - 'ELE_S_DG_DB_Lite.esp'
  - name: 'ELE_Fs_Wt_Lite.esp'
    after:
      - 'ELE_S_Lite'
      - 'ELE_DG_Lite'
      - 'ELE_HF_Lite'
      - 'ELE_DB_Lite'
  - name: 'ELE_Legendary_Lite.esp'
    global_priority: 75            
  - name: 'ELE_Legendary_Fs_Wt_Lite.esp'
    global_priority: 75
```

### Dark Dungeons
```yaml  plugins:
  - name: 'Dark Dungeons for Skyrim-Dawnguard-Dragonborn.esp'
    global_priority: 75
```

### Remaining userlist
```yaml
plugins:
  - name: 'Complete Crafting_TrueWeaponsLvlLists.esp'
    after:
      - 'ELFXEnhancer.esp'
      - 'Dark Dungeons for Skyrim-Dawnguard-Dragonborn.esp'
      - 'ELE_Legendary_Lite.esp'
  - name: 'Vanilla Weather - Merged.esp'
    after:
      - 'WetandCold - Ashes.esp'
  - name: 'Vivid Weathers Merge.esp'
    after:
      - 'WetandCold - Ashes.esp'
  - name: 'SMIM-Merged-All.esp'
    after:
      - 'Blowing in the Wind.esp'
  - name: 'Groundup.esp'
    after:
      - 'Alternate Start - Live Another Life.esp'
  - name: 'Book Covers Skyrim.esp'
    after:
      - 'Complete Crafting Overhaul_Remade.esp'
  - name: 'ogDiverseDragons2.esp'
    after:
      - 'DeadlyDragons.esp'
  - name: 'Thief skills rebalance for Ordinator.esp'
    after:
      - 'Combat Evolved.esp'
  - name: 'No Dragon LODS.esp'
    after:
      - 'DeadlyDragons.esp'
      - 'ogDiverseDragons2 - Deadly Dragons Patch.esp'
      - 'ogDiverseDragons2.esp'
  - name: 'Skyrim Unbound.esp'
    global_priority: 70
  - name: 'Stealth Skills Rebalanced_COMPLETE.esp'
    after:
      - 'Smithing Perks Overhaul_Remade.esp'
  - name: 'RealisticWaterTwo.esp'
    after:
      - 'BFT Ships and Carriages.esp'
      - 'Realistic Boat Bobbing.esp'
  - name: 'Combat Evolved.esp'
    after:
      - 'DeadlyCombat.esp'
  - name: 'PerkusMaximus_Master.esp'
    after:
      - 'Bikini-MTM.esp'
      - 'CL BladeofSacrifice.esp'
      - 'CL Nettlebane.esp'
      - 'Complete Crafting Overhaul_Remade.esp'
      - 'Faction Crossbows_lvl_list patch.esp'
      - 'HN66_NAILS4ALL.esp'
      - 'imp_helm_legend.esp'
      - 'NightingaleArrows.esp'
      - 'Unique Uniques.esp'
      - 'WetandColdAshes WAFR CCF.esp'
  - name: 'SkyrimCoinReplacerRedux.esp'
    after:
      - 'Complete Alchemy & Cooking Overhaul.esp'
      - 'Complete Crafting Overhaul_Remade.esp'
  - name: 'Enhanced Interiors Radioactive.esp'
    after:
      - 'Enhanced Interiors USAIO ELFX Patch.esp'
  - name: 'RelightingSkyrim-FULL.esp'
    after:
      - 'ELFX - Exteriors.esp'
  - name: 'OBISDB.esp'
    after:
      - 'OBIS.esp'
  - name: 'DungeonQuestAwareness.esp'
    after:
      - 'Atlas Legendary.esp'
  - name: 'Wildcat - Combat of Skyrim.esp'
    after:
      - 'DeadlyCombat.esp'
  - name: 'Immersive Citizens - AI Overhaul.esp'
    global_priority: 40
    after:
      - 'Alternate Start - Live Another Life.esp'
      - 'Alternate Start -- New Beginnings.esp'
  - name: 'LSFX-Audiosettings.esp'
    after:
      - 'Reverb and Ambiance Overhaul - Skyrim.esp'
  - name: 'Enhanced Interiors USAIO ELFX Patch.esp'
    after:
      - 'Enhanced Interiors Taverns with ELFX.esp'
      - 'EnhancedLightsandFX.esp'
      - 'iWil_UselessShopOverhaul.esp'
  - name: 'mslVampiricThirst.esp'
    after:
      - 'RaceCompatibilityUSKPOverride.esp'
  - name: 'PerkusMaximus_Thief.esp'
    after:
      - 'PerkusMaximus_Mage.esp'
  - name: 'Enhanced Interiors Taverns with ELFX.esp'
    after:
      - 'Enhanced Interiors Longhouses.esp'
  - name: 'EnhancedLightsandFX.esp'
    after:
      - 'Blowing in the Wind.esp'
      - 'HN66 SLEEK Outfits.esp'
      - 'iWil_UselessShopOverhaul.esp'
      - 'SMIM-Merged-All.esp'
  - name: 'Better Vampires.esp'
    after:
      - 'RaceCompatibilityUSKPOverride.esp'
  - name: 'SnowFall Weathers.esp'
    after:
      - 'WetandCold - Ashes.esp'
  - name: 'Settlements Expanded.esp'
    after:
      - 'Soljund''s Sinkhole.esp'
      - 'Whistling Mine.esp'
  - name: 'Immersive Sounds - Compendium.esp'
    after:
      - 'AOS.esp'
      - 'RUSTIC SOULGEMS - Unsorted.esp'
  - name: 'Subtle but Classless.esp'
    after:
      - 'ethereal_elven_overhaul.esp'
  - name: 'RDO - Cutting Room Floor Patch.esp'
    after:
      - 'Relationship Dialogue Overhaul.esp'
  - name: 'Reverb and Ambiance Overhaul - Skyrim.esp'
    after:
      - 'RelightingSkyrim-FULL.esp'
  - name: 'ELFX - Exteriors.esp'
    after:
      - 'EnhancedLightsandFX.esp'
  - name: 'Dark Fantasy Overhaul.esp'
    after:
      - 'SFO - Dragonborn.esp'
      - 'Skyrim Flora Overhaul.esp'
  - name: 'College of Winterhold NPC Impovement.esp'
    after:
      - 'ethereal_elven_overhaul.esp'
  - name: 'Relationship Dialogue Overhaul.esp'
    after:
      - 'Alternate Start - Live Another Life.esp'
      - 'Guard Dialogue Overhaul.esp'
      - 'GuardAnimationsGDO.esp'
      - 'Skyrim Unbound.esp'
  - name: 'PrinceandPauper.esp'
    after:
      - 'RSChildren.esp'
  - name: 'Weapons & Armor Fixes_Remade.esp'
    after:
      - 'AmazingFollowerTweaks.esp'
  - name: 'PerMa Patches.esp'
    after:
      - 'ELFXEnhancer.esp'
  - name: 'PerkusMaximus_Warrior.esp'
    after:
      - 'PerkusMaximus_Thief.esp'
  - name: 'PerkusMaximus_CombatPlus.esp'
    after:
      - 'PerkusMaximus_Warrior.esp'
  - name: 'Provincial Courier Service.esp'
    after:
      - 'Groundup.esp'
  - name: 'Complete Alchemy & Cooking Overhaul.esp'
    after:
      - 'Ordinator - Perks of Skyrim.esp'
  - name: 'PathOfSorcery.esp'
    after:
      - 'AOS.esp'
      - 'Immersive Sounds - Compendium.esp'
      - 'Smithing Perks Overhaul_Remade.esp'
  - name: 'Aurora - Standing Stones of Skyrim.esp'
    after:
      - 'Disparity.esp'
  - name: 'Summermyst_CCOR_TrueWeaponsLvlLists.esp'
    after:
      - 'Dark Dungeons for Skyrim-Dawnguard-Dragonborn.esp'
      - 'ELE_Legendary_Lite.esp'
      - 'ELFXEnhancer.esp'
  - name: 'NPC_Overhaul_V_3_.esp'
    after:
      - 'AmazingFollowerTweaks.esp'
      - 'ElderOutfit.esp'
  - name: 'Imperious - Races of Skyrim.esp'
    after:
      - 'Subtle but Classless.esp'
  - name: 'Serana Dialogue Edit.esp'
    after:
      - 'RDO - Cutting Room Floor Patch.esp'
      - 'Relationship Dialogue Overhaul.esp'
  - name: 'Blowing in the Wind.esp'
    after:
      - 'RelightingSkyrim_Legendary.esp'
  - name: 'BSHeartland.esm'
    after:
      - 'BSAssets.esm'
  - name: 'ethereal_elven_overhaul.esp'
    after:
      - 'DIVERSE SKYRIM.esp'
  - name: 'DIVERSE SKYRIM.esp'
    after:
      - 'ElderOutfit.esp'
```
