### ISSUE TITLE
Scarcity

### ISSUE THREAD

**Issue by Freso** [loot/skyrim#143]
@LordOfLA also told me that Scarcity should probably load near the end of the load order and gave me this userlist:
```yaml
plugins:
  - name: 'Scarcity - Less Loot Mod.esp'
    global_priority: 77
  - name: 'Scarcity - 2x Loot Rarity.esp'
    global_priority: 78
  - name: 'Scarcity - 4x Loot Rarity.esp'
    global_priority: 78
  - name: 'Scarcity - 6x Loot Rarity.esp'
    global_priority: 78
  - name: 'Scarcity - 8x Loot Rarity.esp'
    global_priority: 78
  - name: 'Scarcity - 10x Loot Rarity.esp'
    global_priority: 78
  - name: 'Scarcity - 2x Merchant Item Rarity.esp'
    global_priority: 79
  - name: 'Scarcity - 4x Merchant Item Rarity.esp'
    global_priority: 79
  - name: 'Scarcity - 6x Merchant Item Rarity.esp'
    global_priority: 79            
  - name: 'Scarcity - 8x Merchant Item Rarity.esp'
    global_priority: 79
  - name: 'Scarcity - 10x Merchant Item Rarity.esp'
    global_priority: 79
```
After some discussion about it, it should probably look something like this if it gets added:
```yaml
  - name: 'Scarcity - Less Loot Mod.esp'
    url: [ '…' ]
    global_priority: 75
  - name: 'Scarcity - (2|4|6|8|10)x (Loot|Merchant Item) Rarity\.esp'
    url: [ '…' ]
    global_priority: 75
    after: [ 'Scarcity - Less Loot Mod.esp' ]
```
