### ISSUE TITLE
duplicate keys

### ISSUE THREAD

**Issue by TanninOne** [loot/skyrim#147]
The masterlist.yaml contains entries with duplicate keys like this:

```
- name: 'ClimatesOfTamriel.esm'
    after:
      - 'Skyrim Project Optimization.esm'
      - 'Skyrim Project Optimization - Dawnguard.esm'
      - 'Skyrim Project Optimization - Dragonborn.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xc110b173
        itm: 4
        udr: 0
    msg:
      - type: warn
        condition: 'checksum("ClimatesOfTamriel.esm",C30AB34E)'
        content: 'This plugin has improperly numbered FormIDs and may have some corruption because it was made with an older version (4.2 or 4.3.x) of TESVSnip.  Please use the [updated plugin](http://www.nexusmods.com/skyrim/mods/17802).'
       ...
    dirty:
      - crc: 0xc110b173
        <<: *dirtyPlugin
        itm: 4
```

has two dirty keys.
The yaml spec (unlike json) requires keys to be unique and so a conformant parser will throw an error, refusing to load this file. Would it be possible to check this during validation?
I assume the yaml parser used by loot is less strict but is there documentation on how it deals with duplicate keys? does it take the first, the last, merge?

**Comment by Freso** [comment]
Huh. I thought one of the checks was for YAML validity. I have a YAML validity check in my `pre-commit` git hook (`ruby -e "require 'yaml'; YAML.load_file('masterlist.yaml')" || exit $?`), but it doesn't seem to complain about the current Skyrim masterlist. :/ (Edit: `python3 -c 'import yaml; yaml.load(open("masterlist.yaml"))'` also doesn't seem to complain.)

The LOOT API documentation describes the [merging behaviour if a plugin is given two (or more) times in the masterlist](http://loot-api.readthedocs.io/en/stable/metadata/data_structures/plugin.html?highlight=merge#merging-behaviour), so it's not directly about how LOOT behaves if a single plugin has multiple instances of given metadata. I don't that specifically is described anywhere (probably because it shouldn't happen, as you say), but maybe the behaviour is the same as for multiple plugins? For the specific case of `ClimatesOfTamriel.esm` that you mention, the two `dirty` entries are actually completely functionally identical, so it doesn't really matter which way the overriding happens.

**Comment by Ortham** [comment]
I expected the YAML parser to fail, but sure enough it's a [known issue](https://github.com/jbeder/yaml-cpp/issues/60) with apparently no resolution in sight. It looks like the first instance of the key is used.

Given that it's a parser noncompliance issue, I'm not sure what can reasonably be done about it within the LOOT API itself... @TanninOne what YAML parser are you using that does fail due to the non-unique key? Maybe we can just add a second parsing step to the Travis run.

**Comment by Freso** [comment]
I've found the Perl module [`Test::YAML::Valid`](https://metacpan.org/pod/Test::YAML::Valid) to be able to tell me that the Skyrim SE masterlist is not valid YAML (using `perl -e 'use Test::More tests => 1; use Test::YAML::Valid; yaml_file_ok("masterlist.yaml"); done_testing()'`), but it also says that all the other masterlists are not valid. I made a `test.yaml` file, which it does report as being valid though:
```yaml
common:
  - name: '../f4se_loader.exe'
    display: '[F4SE](http://f4se.silverlock.org)'
```
So the validation does work to some degree, but maybe it doesn't support the full YAML specification—or maybe all our masterlists are actually currently non-valid YAML. 🙈

(Edit: Also, the Perl command's output is very sparse and just says whether the file is valid or not, not giving any indication where or how the file is not valid, so not very useful as a debugging tool.)
