### ISSUE TITLE
Cleaning info for Dirty plugins

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrim#348]
https://discordapp.com/channels/473542112974077963/473721823071043585/662868121652297729

[The Shadow of The Underking](https://www.nexusmods.com/skyrim/mods/38955)

```yaml
  - name: 'SancreTor.esp'
    dirty:
      - <<: *quickClean
        crc: 0x6BECC749
        util: '[TES5Edit v4.0.1](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 4573
        udr: 54
    clean:
      - crc: 0x8B331989
        util: 'TES5Edit v4.0.1'
```

---

[Solemn Keep Chronicles - Shimmerfall Springs](https://www.nexusmods.com/skyrim/mods/83291/?)

```yaml
  - name: 'SolemnKeep.esp'
    dirty:
      - <<: *quickClean
        crc: 0x3C44B4B0
        util: '[TES5Edit v4.0.1](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 31
    clean:
      - crc: 0xE24E37A9
        util: 'TES5Edit v4.0.1'
```
