### ISSUE TITLE
FNIS missing error

### ISSUE THREAD

**Issue by mizarddo** [loot/skyrim#355]
I have recently replaced FNIS with Nemesis engine to use advanced behavior mods. I'm on the latest LOOT version and I get the FNIS missing error which I think should not show up when Nemesis is present.

**Comment by MacSplody** [comment]
> I have recently replaced FNIS with Nemesis engine to use advanced behavior mods. I'm on the latest LOOT version and I get the FNIS missing error which I think should not show up when Nemesis is present.

The Skyrim SE masterlist has this condition to deal with that situation.

```yaml
  - &FNIS
    name: 'tools/GenerateFNIS_for_Users/GenerateFNISforUsers.exe'
    display: '[Fores New Idles in Skyrim SE](https://www.nexusmods.com/skyrimspecialedition/mods/3038)'
    condition: 'not file("Nemesis_Engine/Nemesis Unlimited Behavior Engine.exe")'
```

Assuming the folder/exe are always using the same name.
It should just be a case of adding that condition to the file entry for FNIS in the LE masterlist.
