### ISSUE TITLE
Reevaluate unaliased messages - Climates Of Tamriel

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrim#453]
Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &useInstead
    type: warn
    content:
      - lang: en
        text: 'Use %1% instead.'
```

---

# Plugins reevaluated:
- [x] ClimatesOfTamriel.esm
- [x] ClimatesOfTamriel-Dawnguard-Patch.esp
- [x] ClimatesOfTamriel-Dragonborn-Patch.esp
- [x] ClimatesOfTamriel-Dungeons-Hardcore.esp
- [x] ClimatesOfTamriel-Dungeons-Hazardous.esp
- [x] ClimatesOfTamriel-Interiors-Cold.esp
- [x] ClimatesOfTamriel-Interiors-Warm.esp
- [x] ClimatesOfTamriel-WinterEdition.esp
- [x] ExpandedSnowSystems.esp
- [x] ClimatesOfTamriel-Sound.esp

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'ClimatesOfTamriel.esm'
    url: [ 'https://www.nexusmods.com/skyrim/mods/17802' ]
    after:
      - 'Skyrim Project Optimization.esm'
      - 'Skyrim Project Optimization - Dawnguard.esm'
      - 'Skyrim Project Optimization - Dragonborn.esm'
    msg:
      - type: warn
        condition: 'checksum("ClimatesOfTamriel.esm",C30AB34E)'
        content:
          - lang: en
            text: 'This plugin has improperly numbered FormIDs and may have some corruption because it was made with an older version (4.2 or 4.3.x) of TESVSnip.  Please use the [updated plugin](http://www.nexusmods.com/skyrim/mods/17802).'
          - lang: de
            text: 'Dieses Plugin hat falsch nummerierte FormIDs und ist möglicherweise beschädigt, da es mit einer älteren Version (4.2 or 4.3.x) von TESVSnip erstellt wurde. Bitte benutzten Sie das [aktualisierte Plugin](http://www.nexusmods.com/skyrim/mods/17802).'
          - lang: ja
            text: 'このプラグインには不正な番号のFormIDが存在します。破損しているデータもあるかもしれません。これは古いバージョン(4.2 か 4.3.x)のTESVSnipで作られているためです。[最新版のプラグイン](http://www.nexusmods.com/skyrim/mods/17802)を使用してください。'
    dirty:
      - <<: *quickClean
        crc: 0xDF772E21
        util: '[TES5Edit v4.0.2f](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 8

  - name: 'ClimatesOfTamriel-Dawnguard-Patch.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/17802' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This plugin has improperly numbered FormIDs and may have some corruption because it was made with an older version (4.2 or 4.3.x) of TESVSnip.  A fixed version has been sent to the author.  Please look for an update.'
          - lang: de
            text: 'Dieses Plugin hat falsch nummerierte FormIDs und ist möglicherweise beschädigt, da es mit einer älteren Version (4.2 oder 4.3.x) von TESVSnip erstellt wurde. Eine reparierte Version wurde an den Autor gesendet. Bitte suchen Sie nach einem Update.'
          - lang: ja
            text: 'このプラグインには不正な番号のFormIDが存在します。破損しているデータもあるかもしれません。これは古いバージョン(4.2 か 4.3.x)のTESVSnipで作られているためです。製作者まで修正版が送られていますので、今後の更新をお待ちください。'
        condition: 'checksum("ClimatesOfTamriel-Dawnguard-Patch.esp",8F78567C)'
    clean:
      - crc: 0x9D7312A5
        util: 'TES5Edit v4.0.2f'

  - name: 'ClimatesOfTamriel-Dragonborn-Patch.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/17802' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This plugin has improperly numbered FormIDs and may have some corruption because it was made with an older version (4.2 or 4.3.x) of TESVSnip.  A fixed version has been sent to the author.  Please look for an update.'
          - lang: de
            text: 'Dieses Plugin hat falsch nummerierte FormIDs und ist möglicherweise beschädigt, da es mit einer älteren Version (4.2 oder 4.3.x) von TESVSnip erstellt wurde. Eine reparierte Version wurde an den Autor gesendet. Bitte suchen Sie nach einem Update.'
          - lang: ja
            text: 'このプラグインには不正な番号のFormIDが存在します。破損しているデータもあるかもしれません。これは古いバージョン(4.2 か 4.3.x)のTESVSnipで作られているためです。製作者まで修正版が送られていますので、今後の更新をお待ちください。'
        condition: 'checksum("ClimatesOfTamriel-Dragonborn-Patch.esp",81CF7754)'
    clean:
      - crc: 0x9FFF2A85
        util: 'TES5Edit v4.0.2f'

  - name: 'ClimatesOfTamriel-Dungeons-Hardcore.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/17802' ]
    inc:
      - 'ClimatesOfTamriel-Dungeons-Hazardous.esp'
      - 'Realistic Lighting Overhaul - Dungeons.esp'
      - 'Realistic Lighting Overhaul - Brighter Dungeons.esp'
      - 'Realistic Lighting Overhaul - Dungeon Lighting.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This plugin has improperly numbered FormIDs and may have some corruption because it was made with an older version (4.2 or 4.3.x) of TESVSnip.  A fixed version has been sent to the author.  Please look for an update.'
          - lang: de
            text: 'Dieses Plugin hat falsch nummerierte FormIDs und ist möglicherweise beschädigt, da es mit einer älteren Version (4.2 oder 4.3.x) von TESVSnip erstellt wurde. Eine reparierte Version wurde an den Autor gesendet. Bitte suchen Sie nach einem Update.'
          - lang: ja
            text: 'このプラグインには不正な番号のFormIDが存在します。破損しているデータもあるかもしれません。これは古いバージョン(4.2 か 4.3.x)のTESVSnipで作られているためです。製作者まで修正版が送られていますので、今後の更新をお待ちください。'
        condition: 'checksum("ClimatesOfTamriel-Dungeons-Hardcore.esp", 4EEA922F)'
    dirty:
      - <<: *quickClean
        crc: 0x67CA961C
        util: '[TES5Edit v4.0.2f](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 2

  - name: 'ClimatesOfTamriel-Dungeons-Hazardous.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/17802' ]
    inc:
      - 'ClimatesOfTamriel-Dungeons-Hardcore.esp'
      - 'Realistic Lighting Overhaul - Dungeons.esp'
      - 'Realistic Lighting Overhaul - Brighter Dungeons.esp'
      - 'Realistic Lighting Overhaul - Dungeon Lighting.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This plugin has improperly numbered FormIDs and may have some corruption because it was made with an older version (4.2 or 4.3.x) of TESVSnip.  A fixed version has been sent to the author.  Please look for an update.'
          - lang: de
            text: 'Dieses Plugin hat falsch nummerierte FormIDs und ist möglicherweise beschädigt, da es mit einer älteren Version (4.2 oder 4.3.x) von TESVSnip erstellt wurde. Eine reparierte Version wurde an den Autor gesendet. Bitte suchen Sie nach einem Update.'
          - lang: ja
            text: 'このプラグインには不正な番号のFormIDが存在します。破損しているデータもあるかもしれません。これは古いバージョン(4.2 か 4.3.x)のTESVSnipで作られているためです。製作者まで修正版が送られていますので、今後の更新をお待ちください。'
        condition: 'checksum("ClimatesOfTamriel-Dungeons-Hazardous.esp",CBE304CE)'
    clean:
      - crc: 0xBDC66F4C
        util: 'TES5Edit v4.0.2f'

  - name: 'ClimatesOfTamriel-Interiors-Cold.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/17802' ]
    inc:
      - 'ClimatesOfTamriel-Interiors-Warm.esp'
      - 'Realistic Lighting Overhaul - Major City Interiors.esp'
      - 'Realistic Lighting Overhaul - Minor Cities and Town Interiors.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This plugin has improperly numbered FormIDs and may have some corruption because it was made with an older version (4.2 or 4.3.x) of TESVSnip.  A fixed version has been sent to the author.  Please look for an update.'
          - lang: de
            text: 'Dieses Plugin hat falsch nummerierte FormIDs und ist möglicherweise beschädigt, da es mit einer älteren Version (4.2 oder 4.3.x) von TESVSnip erstellt wurde. Eine reparierte Version wurde an den Autor gesendet. Bitte suchen Sie nach einem Update.'
          - lang: ja
            text: 'このプラグインには不正な番号のFormIDが存在します。破損しているデータもあるかもしれません。これは古いバージョン(4.2 か 4.3.x)のTESVSnipで作られているためです。製作者まで修正版が送られていますので、今後の更新をお待ちください。'
        condition: 'checksum("ClimatesOfTamriel-Interiors-Cold.esp",84DB3F8)'
    clean:
      - crc: 0x80B61351
        util: 'TES5Edit v4.0.2f'

  - name: 'ClimatesOfTamriel-Interiors-Warm.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/17802' ]
    inc:
      - 'ClimatesOfTamriel-Interiors-Cold.esp'
      - 'Realistic Lighting Overhaul - Major City Interiors.esp'
      - 'Realistic Lighting Overhaul - Minor Cities and Town Interiors.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This plugin has improperly numbered FormIDs and may have some corruption because it was made with an older version (4.2 or 4.3.x) of TESVSnip.  A fixed version has been sent to the author.  Please look for an update.'
          - lang: de
            text: 'Dieses Plugin hat falsch nummerierte FormIDs und ist möglicherweise beschädigt, da es mit einer älteren Version (4.2 oder 4.3.x) von TESVSnip erstellt wurde. Eine reparierte Version wurde an den Autor gesendet. Bitte suchen Sie nach einem Update.'
          - lang: ja
            text: 'このプラグインには不正な番号のFormIDが存在します。破損しているデータもあるかもしれません。これは古いバージョン(4.2 か 4.3.x)のTESVSnipで作られているためです。製作者まで修正版が送られていますので、今後の更新をお待ちください。'
        condition: 'checksum("ClimatesOfTamriel-Interiors-Warm.esp",77C47623)'
    clean:
      - crc: 0xB61E85AE
        util: 'TES5Edit v4.0.2f'

  - name: 'ClimatesOfTamriel-WinterEdition.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/17802' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This plugin has improperly numbered FormIDs and may have some corruption because it was made with an older version (4.2 or 4.3.x) of TESVSnip.  A fixed version has been sent to the author.  Please look for an update.'
          - lang: de
            text: 'Dieses Plugin hat falsch nummerierte FormIDs und ist möglicherweise beschädigt, da es mit einer älteren Version (4.2 oder 4.3.x) von TESVSnip erstellt wurde. Eine reparierte Version wurde an den Autor gesendet. Bitte suchen Sie nach einem Update.'
          - lang: ja
            text: 'このプラグインには不正な番号のFormIDが存在します。破損しているデータもあるかもしれません。これは古いバージョン(4.2 か 4.3.x)のTESVSnipで作られているためです。製作者まで修正版が送られていますので、今後の更新をお待ちください。'
        condition: 'checksum("ClimatesOfTamriel-WinterEdition.esp",74DF3C5)'
    clean:
      - crc: 0x1675469B
        util: 'TES5Edit v4.0.2f'

  - name: 'ExpandedSnowSystems.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/28016' ]
    msg:
      - <<: *useVersionDawnguard
        condition: 'active("Dawnguard.esm") and not active("Dragonborn.esm") and ( checksum("ExpandedSnowSystems.esp",DB538BE0) or checksum("ExpandedSnowSystems.esp",74DF9966) )'
      - type: warn
        content:
          - lang: en
            text: 'ClimatesOfTamriel.esm is present or is active. Use ExpandedSnowSystems-CoT.esp instead to have mod work as intended.'
          - lang: de
            text: 'ClimatesOfTamriel.esm ist vorhanden oder aktiv. Verwenden Sie stattdessen ExpandedSnowSystems-CoT.esp, damit die Mod wie vorgesehen funktioniert.'
          - lang: ja
            text: 'ClimatesOfTamriel.esmが存在するかアクティブになっています。代わりにExpandedSnowSystems-CoT.espを使用しなければ正しく動作しません。'
        condition: 'active("ClimatesOfTamriel.esm")'
    clean:
      # v1.4 - DG and DB
      - crc: 0x74DF9966
        util: 'TES5Edit v4.0.2i'
      # v1.3 - No DG
      - crc: 0xDB538BE0
        util: 'TES5Edit v4.0.2i'
      # v1.3 - DG
      - crc: 0xB7A24777
        util: 'TES5Edit v4.0.2i'

  - name: 'ClimatesOfTamriel-Sound.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This plugin has improperly numbered FormIDs and may have some corruption because it was made with an older version (4.2 or 4.3.x) of TESVSnip.  A fixed version has been sent to the author.  Please look for an update.'
          - lang: de
            text: 'Dieses Plugin hat falsch nummerierte FormIDs und ist möglicherweise beschädigt, da es mit einer älteren Version (4.2 oder 4.3.x) von TESVSnip erstellt wurde. Eine ausgebesserte Version wurde an den Autor gesendet. Bitte suchen Sie nach einem Update.'
          - lang: ja
            text: 'このプラグインには不正な番号のFormIDが存在します。破損しているデータもあるかもしれません。これは古いバージョン(4.2 か 4.3.x)のTESVSnipで作られているためです。製作者まで修正版が送られていますので、今後の更新をお待ちください。'
        condition: 'checksum("ClimatesOfTamriel-Sound.esp",47AF2A0B)'
```

</details>
