### ISSUE TITLE
Reevaluate unaliased messages - T3nd0

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrim#455]
Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &renameFile
    type: say
    content:
      - lang: en
        text: 'Rename this file to %1%.'
```

---

# Plugins reevaluated:
- [x] T3nd0sOverhaul.esp (unsourceable)
- [x] T3nd0sOverhaulNoLighting.esp (unsourceable)
- [x] [SkyRe_Main.esp](https://www.nexusmods.com/skyrim/mods/9286/)
- [x] [SkyRe_Main_NoDawnguard.esp](https://www.nexusmods.com/skyrim/mods/9286/)
- [x] SkyRe_Comp.esp (presumably [deleted](https://www.nexusmods.com/skyrim/mods/19944))
- [x] PerkReset SkyRe Compatibility Patch.esp (presumably [deleted](https://www.nexusmods.com/skyrim/mods/22070))
- [x] [SkyRe_Lighting.esp](https://www.nexusmods.com/skyrim/mods/9286/)
- [x] SkyRe_StandingStones_Fix.esp (unsourceable)
- [x] SkyRe_Races_Fix.esp (unsourceable)
- [x] [SkyRe_EnemyAI.esp](https://www.nexusmods.com/skyrim/mods/9286/)
- [x] [ReProccerDragonborn.esp](https://www.nexusmods.com/skyrim/mods/27092/)

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'T3nd0sOverhaul.esp'
    msg:
      - *obsolete
      - type: say
        content:
          - lang: en
            text: 'Only for non ENB users'
          - lang: de
            text: 'Nur für Benutzer ohne ENB.'
          - lang: ja
            text: 'ENBを使用しないユーザー向けのプラグインです。'
          - lang: ru
            text: 'Для не ENB-пользователей.'

  - name: 'T3nd0sOverhaulNoLighting.esp'
    inc: [ 'T3nd0sOverhaul.esp' ]
    msg:
      - *obsolete
      - type: say
        content:
          - lang: en
            text: 'Only for ENB users'
          - lang: de
            text: 'Nur für Benutzer mit ENB.'
          - lang: ja
            text: 'ENBを使用しないユーザー向けのプラグインです。'
          - lang: ru
            text: 'Только для не ENB пользователей.'

  - name: 'SkyRe_Comp.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'It is recommended to use [PerkReset SkyRe Compatibility Patch.esp](http://www.nexusmods.com/skyrim/mods/22070) instead.'
          - lang: de
            text: 'Es wird empfohlen, dass Sie stattdessen [PerkReset SkyRe Compatibility Patch.esp] (http://www.nexusmods.com/skyrim/mods/22070) verwenden.'
          - lang: ja
            text: '[PerkReset SkyRe Compatibility Patch.esp](http://www.nexusmods.com/skyrim/mods/22070)を代わりに使用することを推奨します。'
          - lang: ru
            text: 'Рекомендуется использовать вместо этого [PerkReset SkyRe Compatibility Patch.esp](http://www.nexusmods.com/skyrim/mods/22070).'
        condition: 'not file("PerkReset SkyRe Compatibility Patch.esp")'
      - type: error
        content:
          - lang: en
            text: 'Delete and use ''PerkReset SkyRe Compatibility Patch.esp'' instead.'
          - lang: de
            text: 'Löschen und verwenden Sie stattdessen ''PerkReset SkyRe Compatibility Patch.esp''.'
          - lang: ja
            text: 'このプラグインを削除し、''PerkReset SkyRe Compatibility Patch.esp''を代わりに使用してください。'
          - lang: ru
            text: 'Удалите и используйте вместо этого ''PerkReset SkyRe Compatibility Patch.esp''.'
        condition: 'file("PerkReset SkyRe Compatibility Patch.esp")'
      - type: warn
        content:
          - lang: en
            text: 'Rename ''PerkReset.esp'' to ''PerkReset.esm''.'
          - lang: de
            text: 'Benennen Sie ''PerkReset.esp'' in ''PerkReset.esm'' um.'
          - lang: ja
            text: '現在の''PerkReset.esp''を''PerkReset.esm''にリネームしてください。'
          - lang: ru
            text: 'Переименуйте ваш ''PerkReset.esp'' в ''PerkReset.esm''.'
        condition: 'file("PerkReset.esp")'

  - name: 'PerkReset SkyRe Compatibility Patch.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Rename ''PerkReset.esp'' to ''PerkReset.esm''.'
          - lang: de
            text: 'Benennen Sie ''PerkReset.esp'' in ''PerkReset.esm'' um.'
          - lang: ja
            text: '現在の''PerkReset.esp''を''PerkReset.esm''にリネームしてください。'
          - lang: ru
            text: 'Переименуйте ваш ''PerkReset.esp'' в ''PerkReset.esm''.'
        condition: 'file("PerkReset.esp")'

  - name: 'SkyRe_StandingStones_Fix.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'This mod is meant to be used with the Races module of SkyRe. The game should generally work fine without it, but the effect from the Lady Standing Stone may not behave as expected.'
          - lang: de
            text: 'Diese Mod soll mit dem Rassen Modul von SkyRe verwendet werden. Das Spiel sollte generell auch ohne gut funktionieren, aber der Effekt vom Lady Standing Stone verhält sich möglicherweise nicht wie erwartet.'
          - lang: ja
            text: 'このModはSkyReの種族用モジュール（Races module）との使用を想定されています。モジュール抜きでも全体的に問題なく動作しますが、淑女の石碑から得られる効果が正しく発揮されない可能性があります。'
        condition: 'not active("SkyRe_Races.esp")'

  - name: 'SkyRe_Races_Fix.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'This mod is meant to be used with the Races module of SkyRe. The game should work fine without it, but the Khajiit "Claws" effect will have a wrong description.'
          - lang: de
            text: 'Diese Mod soll mit dem Rassen-Modul von SkyRe verwendet werden. Das Spiel sollte ohne es gut funktionieren, aber der Khajiit "Claws" Effekt wird eine falsche Beschreibung haben.'
          - lang: ja
            text: 'このModはSkyReの種族用モジュール（Races module）との使用を想定されています。プラグインが欠けていても機能しますが、カジートの「爪」の効果説明が本来と異なってしまいます。'
        condition: 'not active("SkyRe_Races.esp")'

  - name: 'SkyRe_Main.esp'
    req: [ *SKSE ]
    inc:
      - 'ACE Crafting.esp'
      - 'ACE Speech.esp'
      - 'Perky.esp'
      - 'Crafting300.esp'
      - 'Complete Crafting Overhaul.esp'
      - 'Complete Crafting Overhaul - BS version.esp'
      - 'PerkUP-Alchemy.esp'
      - 'PerkUP-Alteration.esp'
      - 'PerkUP-Archery.esp'
      - 'PerkUP-Block.esp'
      - 'PerkUP-Conjuration.esp'
      - 'PerkUP-Destruction.esp'
      - 'PerkUP-Enchanting.esp'
      - 'PerkUP-HeavyArmor.esp'
      - 'PerkUP-Illusion.esp'
      - 'PerkUP-LightArmor.esp'
      - 'PerkUP-Lockpicking.esp'
      - 'PerkUP-OneHanded.esp'
      - 'PerkUP-Pickpocket.esp'
      - 'PerkUP-Restoration.esp'
      - 'PerkUP-Smithing.esp'
      - 'PerkUP-Sneak.esp'
      - 'PerkUP-Speech.esp'
      - 'PerkUP-TwoHanded.esp'
      - 'PerkUP-zOptional-Pickpocket_CarryMore100.esp'
      - 'PerkUP-zOptional_HeavyArmor_NoHelmsReq.esp'
      - 'PerkUP-zOptional_LightArmor_NoHelmsReq.esp'
      - 'Uncapped Perks - Combat + Stealth.esp'
      - 'Uncapped Perks - Magic.esp'
      - 'Uncapped Perks - Alchemy.esp'
      - 'Uncapped Perks - Alteration.esp'
      - 'Uncapped Perks - Archery.esp'
      - 'Uncapped Perks - Block.esp'
      - 'Uncapped Perks - Conjuration.esp'
      - 'Uncapped Perks - Destruction.esp'
      - 'Uncapped Perks - Enchanting.esp'
      - 'Uncapped Perks - Heavy Armor.esp'
      - 'Uncapped Perks - Illusion.esp'
      - 'Uncapped Perks - Light Armor.esp'
      - 'Uncapped Perks - One Handed.esp'
      - 'Uncapped Perks - Pickpocket.esp'
      - 'Uncapped Perks - Restoration.esp'
      - 'Uncapped Perks - Sneak.esp'
      - 'Uncapped Perks - Speech.esp'
      - 'Uncapped Perks - Two Handed.esp'
    after: [ 'Scoped Bows.esp' ]
    msg:
      - <<: *requiresX
        condition: 'not file("SKSE/Plugins/SKSE_Elys_Uncapper.dll")'
        subs: [ '[Skyrim -Community- Uncapper](http://www.nexusmods.com/skyrim/mods/1175) for full perk functionality' ]
      - type: say
        content:
          - lang: en
            text: 'If lockpicking is not working, try to delete ''interface/lockpickingmenu.swf''.'
          - lang: de
            text: 'Wenn Schlösserknacken nicht funktioniert, versuchen Sie ''interface/lockpickingmenu.swf'' Zu löschen.'
          - lang: es
            text: 'Si lockpicking no funciona intenta borrar ''interface/lockpickingmenu.swf''.'
          - lang: ja
            text: '開錠ができなくなった場合は''interface/lockpickingmenu.swf''を削除してみてください。'
          - lang: ru
            text: 'Если вы не можете взломать замки, не появляется окно со взломом, то попробуйте удалить или переименовать файл ''interface/lockpickingmenu.swf''.'
        condition: 'file("interface/lockpickingmenu.swf")'
      - type: say
        content:
          - lang: en
            text: 'If you have a problem with aiming, try to install [this](http://www.nexusmods.com/skyrim/mods/13652) mod.'
          - lang: de
            text: 'Wenn Sie ein Problem mit dem Zielen haben, versuchen Sie [diese](http://www.nexusmods.com/skyrim/mods/13652) Mod zu installieren.'
          - lang: es
            text: 'Si tienes problemas al apuntar intenta instalar [este](http://www.nexusmods.com/skyrim/mods/13652) mod.'
          - lang: ja
            text: '狙いを上手くつけられない場合は[こちら](http://www.nexusmods.com/skyrim/mods/13652)のModをインストールしてみてください。'
          - lang: ru
            text: 'Если у вас проблемы с прицеливанием, попробуйте установить [этот](http://www.nexusmods.com/skyrim/mods/13652) мод.'
        condition: 'not file("Proper Aiming.esp")'
      - type: say
        content:
          - lang: en
            text: 'To make aiming easier add the following lines to Skyrim.ini: %1%'
          - lang: de
            text: 'Um das Zielen zu vereinfachen, fügen Sie die folgenden Zeilen zu Skyrim.ini hinzu: %1%'
          - lang: es
            text: 'Para hacer apuntar más fácil agrega estas líneas a Skyrim.ini: %1%'
          - lang: ja
            text: '以下の記述をSkyrim.iniに追加すると狙いをつけ易くなります。%1%'
          - lang: ru
            text: 'Чтобы сделать прицеливание проще, добавьте в ваш Skyrim.ini следующие строки: %1%'
        subs:
          - |

            ```
            [Actor]
            fVisibleNavmeshMoveDist=12288.0000

            [Combat]
            f1PArrowTiltUpAngle=0.64
            f3PArrowTiltUpAngle=0.64
            fMagnetismStrafeHeadingMult=0.0
            fMagnetismLookingMult=0.0
            ```
    tag:
      - Delev
      - Relev

  - name: 'SkyRe_Main_NoDawnguard.esp'
    req: [ *SKSE ]
    inc:
      - 'SkyRe_Main.esp'
      - 'Dawnguard.esm'
      - 'ACE Crafting.esp'
      - 'ACE Speech.esp'
      - 'Perky.esp'
      - 'Crafting300.esp'
      - 'Complete Crafting Overhaul.esp'
      - 'Complete Crafting Overhaul - BS version.esp'
      - 'PerkUP-Alchemy.esp'
      - 'PerkUP-Alteration.esp'
      - 'PerkUP-Archery.esp'
      - 'PerkUP-Block.esp'
      - 'PerkUP-Conjuration.esp'
      - 'PerkUP-Destruction.esp'
      - 'PerkUP-Enchanting.esp'
      - 'PerkUP-HeavyArmor.esp'
      - 'PerkUP-Illusion.esp'
      - 'PerkUP-LightArmor.esp'
      - 'PerkUP-Lockpicking.esp'
      - 'PerkUP-OneHanded.esp'
      - 'PerkUP-Pickpocket.esp'
      - 'PerkUP-Restoration.esp'
      - 'PerkUP-Smithing.esp'
      - 'PerkUP-Sneak.esp'
      - 'PerkUP-Speech.esp'
      - 'PerkUP-TwoHanded.esp'
      - 'PerkUP-zOptional-Pickpocket_CarryMore100.esp'
      - 'PerkUP-zOptional_HeavyArmor_NoHelmsReq.esp'
      - 'PerkUP-zOptional_LightArmor_NoHelmsReq.esp'
      - 'Uncapped Perks - Combat + Stealth.esp'
      - 'Uncapped Perks - Magic.esp'
      - 'Uncapped Perks - Alchemy.esp'
      - 'Uncapped Perks - Alteration.esp'
      - 'Uncapped Perks - Archery.esp'
      - 'Uncapped Perks - Block.esp'
      - 'Uncapped Perks - Conjuration.esp'
      - 'Uncapped Perks - Destruction.esp'
      - 'Uncapped Perks - Enchanting.esp'
      - 'Uncapped Perks - Heavy Armor.esp'
      - 'Uncapped Perks - Illusion.esp'
      - 'Uncapped Perks - Light Armor.esp'
      - 'Uncapped Perks - One Handed.esp'
      - 'Uncapped Perks - Pickpocket.esp'
      - 'Uncapped Perks - Restoration.esp'
      - 'Uncapped Perks - Sneak.esp'
      - 'Uncapped Perks - Speech.esp'
      - 'Uncapped Perks - Two Handed.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'The SkyRe has many conflicts with other mods. Please read the readme before playing with mod. This will prevent many problems. Read it [here](http://www.nexusmods.com/skyrim/mods/9286).'
          - lang: de
            text: 'SkyRe hat viele Konflikte mit anderen Mods. Bitte lesen Sie die Readme bevor Sie mit der Mod spielen. Dadurch werden viele Probleme vermieden. Die Readme ist [hier](http://www.nexusmods.com/skyrim/mods/9286) zu finden.'
          - lang: ja
            text: 'SkyReを他のModと併用すると多数の競合が発生します。プレイする前にReadmeの内容を読んでおけば問題の多くを防げるでしょう。[こちら](http://www.nexusmods.com/skyrim/mods/9286)を参照してください。'
          - lang: ru
            text: 'SkyRe имеет много конфликтов с другими модами. Пожалуйста прочтите ридми перед игрой в мод. Это позволит избежать многих проблем. Читайте его [здесь](http://www.nexusmods.com/skyrim/mods/9286)(Англ.).'
      - <<: *requiresX
        condition: 'not file("SKSE/Plugins/SKSE_Elys_Uncapper.dll")'
        subs: [ '[Skyrim -Community- Uncapper](http://www.nexusmods.com/skyrim/mods/1175) for full perk functionality' ]
      - type: say
        content:
          - lang: en
            text: 'If lockpicking is not working, try to delete ''interface/lockpickingmenu.swf'''
          - lang: de
            text: 'Wenn Schlösserknacken nicht funktioniert, versuchen Sie ''interface/lockpickingmenu.swf'' Zu löschen.'
          - lang: ja
            text: '開錠ができなくなった場合は''interface/lockpickingmenu.swf''を削除してみてください。'
          - lang: ru
            text: 'Если вы не можете взломать замки, не появляется окно со взломом, то попробуйте удалить или переименовать файл ''interface/lockpickingmenu.swf'''
        condition: 'file("interface/lockpickingmenu.swf")'
      - type: say
        content:
          - lang: en
            text: 'If you have a problem with aiming, try to install [this](http://www.nexusmods.com/skyrim/mods/13652) mod.'
          - lang: de
            text: 'Wenn Sie ein Problem mit dem Zielen haben, versuchen Sie [diese](http://www.nexusmods.com/skyrim/mods/13652) Mod zu installieren.'
          - lang: ja
            text: '狙いを上手くつけられない場合は[こちら](http://www.nexusmods.com/skyrim/mods/13652)のModをインストールしてみてください。'
          - lang: ru
            text: 'Если у вас проблемы с прицеливанием, попробуйте установить [этот](http://www.nexusmods.com/skyrim/mods/13652) мод.'
      - type: say
        content:
          - lang: en
            text: 'To make aiming easier, add the following lines to Skyrim.ini: %1%'
          - lang: de
            text: 'Um das Zielen zu vereinfachen, fügen Sie die folgenden Zeilen zu Skyrim.ini hinzu: %1%'
          - lang: es
            text: 'Para hacer apuntar más fácil agrega estas líneas a Skyrim.ini: %1%'
          - lang: ja
            text: '次の記述をSkyrim.iniに追加すると狙いをつけ易くなります。%1%'
          - lang: ru
            text: 'Чтобы сделать прицеливание проще, добавьте в ваш Skyrim.ini следующие строки: %1%'
        subs:
          - |

            ```
            [Actor]
            fVisibleNavmeshMoveDist=12288.0000

            [Combat]
            f1PArrowTiltUpAngle=0.64
            f3PArrowTiltUpAngle=0.64
            fMagnetismStrafeHeadingMult=0.0
            fMagnetismLookingMult=0.0
            ```
    tag:
      - Delev
      - Relev

  - name: 'SkyRe_Lighting.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Only for non ENB users'
          - lang: de
            text: 'Nur für Benutzer ohne ENB.'
          - lang: ja
            text: 'ENBを使用しないユーザー向けのプラグインです。'
          - lang: ru
            text: 'Только для не ENB пользователей.'

  - name: 'SkyRe_EnemyAI.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Deactivate ''SkyRe_EnemyAI.esp'' before creation of ASIS patch and activate only after creation of ASIS patch. Or you can add SkyRe_EnemyAI.esp to ASIS''s blocklist.txt ([instructions](https://forums.nexusmods.com/index.php?/topic/563161-t3nd0s-perk-overhaul/page-2922))'
          - lang: de
            text: 'Deaktivieren Sie ''SkyRe_EnemyAI.esp'' vor der Erstellung des ASIS-Patches und aktivieren Sie es erst nach der Erstellung des ASIS-Patches. Oder Sie können SkyRe_EnemyAI.esp zu ASIS''s blocklist.txt hinzufügen ([Anweisungen](https://forums.nexusmods.com/index.php?/topic/563161-t3nd0s-perk-overhaul/page-2922)).'
          - lang: ja
            text: 'ASISでパッチを作成する場合はその前に''SkyRe_EnemyAI.esp''を非アクティブにし、パッチ作成後にアクティブにしてください。SkyRe_EnemyAI.espをASISのblocklist.txt に追加してもいいでしょう。([解説](https://forums.nexusmods.com/index.php?/topic/563161-t3nd0s-perk-overhaul/page-2922))'
          - lang: ru
            text: 'Отключите ''SkyRe_EnemyAI.esp'' перед созданием ASIS-патча и активируйте только после создания.'
        condition: 'active("SkyRe_EnemyAI.esp") and (file("ASIS.esp") or file("ASIS-Dependency.esp"))'

  - name: 'ReProccerDragonborn.esp'
    group: *reproccerGroup
    msg:
      - type: say
        content:
          - lang: en
            text: 'Change the master file of this patch from ReProccer.esp to SUM.esp if using SUM''s merged patch feature.'
          - lang: de
            text: 'Ändern Sie die Masterdatei dieses Patches von ReProccer.esp zu SUM.esp, wenn Sie die Funktion für zusammengeführte Patches von SUM verwenden.'
          - lang: ja
            text: 'SUMのmerged patch機能を使用している場合、このパッチのマスターファイルをReProccer.espからSUM.espに変更してください。'
        condition: 'file("SUM.esp")'
```

</details>
