### ISSUE TITLE
Reevaluate unaliased messages - Body

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrim#456]
Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &requiresResources
    type: warn
    content:
      - lang: en
        text: 'Requires resources (e.g. meshes, textures; not plugins) from %1%.'

  - &requiresX
    type: warn
    content:
      - lang: en
        text: 'Requires: %1%'
```

---

# Plugins reevaluated:
- [x] Lady Body.esp
- [x] [`bouncy_bodices.*\.esp`](https://www.nexusmods.com/skyrim/mods/21271/)
- [x] bouncy_booties.esp (unsourceable)
- [x] bouncy_belts_and_stockings.esp (unsourceable)
- [x] [DemonHunterArmor.esp](https://www.nexusmods.com/skyrim/mods/27060/)
- [x] [MorSit.esp](https://www.nexusmods.com/skyrim/mods/25213/)
- [x] NewmillerCasualBikiniUNP2.esp (unsourceable)
- [x] NewmillerShoesUNP.esp (unsourceable)
- [x] [SeraphineHuntedArmor.esp](https://www.nexusmods.com/skyrim/mods/24723/)
- [x] [FM - UNP Merchants.esp](https://www.nexusmods.com/skyrim/mods/24684/)
- [x] [Companion_Crea.esp](https://www.nexusmods.com/skyrim/mods/24710/)
- [x] [Companion_Lese.esp](https://www.nexusmods.com/skyrim/mods/24710/)
- [x] [Illia.esp](https://www.nexusmods.com/skyrim/mods/13997/)
- [x] Lia.esp (unsourceable)
- [x] iLoveLydia.esp (unsourceable)

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'Lady Body.esp'
    msg:
      - type: warn
        condition: 'version("../TESV.exe","1.7.7",<) and not active("Dawnguard.esm")'
        content:
          - lang: en
            text: 'For Lady Body 1.5 and higher Skyrim 1.7.7 and DLC Dawnguard are required.'
          - lang: de
            text: 'Für Lady Body 1.5 und neuer werden Skyrim 1.7.7 und DLC Dawnguard benötigt.'
          - lang: es
            text: 'Si utilizas Lady Body 1.7 o posterior Skyrim 1.7.7 y Dawnguard DLC son requeridos.'
          - lang: ja
            text: 'Lady Body 1.5、1.7.7以降のSkyrim、Dawnguard DLCが必要です。'
          - lang: ru
            text: 'Для Lady Body 1.5 и выше требуются Skyrim 1.7.7 и DLC Dawnguard.'
      - type: warn
        condition: 'version("../TESV.exe","1.8.151.0.7",<) and not active("Dawnguard.esm") and not active("Dragonborn.esm")'
        content:
          - lang: en
            text: 'For version Lady Body 2.1 and higher Skyrim 1.8.151.0.7, DLC Dawnguard and DLC Dragonborn are required.'
          - lang: de
            text: 'Für Lady Body 2.1 und neuer werden Skyrim 1.8.151.0.7, DLC Dawnguard und DLC Dragonborn benötigt.'
          - lang: es
            text: 'Si utilizas Lady Body 2.1 o posterior Skyrim 1.8.151.0.7, DLC Dawnguard and DLC Dragonborn son requeridos.'
          - lang: ja
            text: 'Lady Body 2.1、1.8.151.0.7以降のSkyrim、Dawnguard DLCおよびDragonborn DLCが必要です。'
          - lang: ru
            text: 'Для версии 2.1 и выше требуется Skyrim 1.8.151.0.7, DLC Dawnguard и DLC Dragonborn.'
      - type: say
        content:
          - lang: en
            text: 'This mod makes Khajiit and Argonian races unplayable. Don''t install this mod if you want to play for Argonian or Khajiit.'
          - lang: de
            text: 'Diese Mod macht Khajiit und Argonier-Rassen unspielbar. Installieren Sie diese Mod nicht, wenn Sie als Argonier oder Khajiit spielen möchten.'
          - lang: es
            text: 'Este mod hace que las razas Khajiit and Argonian races no sean accesibles al jugador. No lo utilizaes si planeas ser un Argonian o Khajit.'
          - lang: ja
            text: 'このModはカジートとアルゴニアン種族をプレイ不能にします。アルゴニアンかカジートで遊ぼうとしている場合はインストールしないでください。'
          - lang: ru
            text: 'С данным модом женский вариант аргониан и хаджитов становятся недоступны игрокам в виде игровых рас! Не ставьте этот мод, если играете/хотите играть зверорасами.'

  - name: 'bouncy_booties.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Be sure you have the correct bouncy_bodices mod installed for this esp.'
          - lang: de
            text: 'Stellen Sie sicher, dass Sie den richtigen bouncy_bodices Mod für diese esp installiert haben.'
          - lang: ja
            text: 'このEspを使用するときは適切なBouncy Bodices系列のModをインストールしてください。'
          - lang: ru
            text: 'Убедитесь, что для этого esp у вас установлена корректная версия мода bouncy_bodices.'

  - name: 'bouncy_belts_and_stockings.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: UNP or UNPB body. Should work with all versions.'
          - lang: de
            text: 'Benötigt: UNP oder UNPB Körper. Sollte mit allen Versionen funktionieren.'
          - lang: ja
            text: '要: UNPかUNPB体型（どのバージョンでも動作します）'
          - lang: ru
            text: 'Требуется: UNP или UNPB. Должно работать со всеми версиями.'

  - name: 'NewmillerCasualBikiniUNP2.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Be sure this is the correct version of this esp for whichever body type you have installed. The esp name is NOT different for each body type.'
          - lang: de
            text: 'Stellen Sie sicher, dass dies die richtige Version dieser esp ist, abhängig davon, welchen Körpertyp Sie installiert haben. Der esp Name ist NICHT für jeden Körpertyp unterschiedlich.'
          - lang: ja
            text: 'このEspは必ずインストールした体型Modとマッチするバージョンのものを使用してください。Espの名前はそれぞれの体型用でまったく同じです。'
          - lang: ru
            text: 'Убедитесь, что используете корректную версию для установленного у вас реплейсера тела, так как esp-файл одинаков для обеих версий.'
      - type: say
        content:
          - lang: en
            text: 'Requires: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) or [CBBE](http://www.nexusmods.com/skyrim/mods/2666) or [UNP Blessed Body (UNPB)](http://www.nexusmods.com/skyrim/mods/37900).'
          - lang: de
            text: 'Benötigt: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) oder [CBBE](http://www.nexusmods.com/skyrim/mods/2666) oder [UNP Blessed Body (UNPB)](http://www.nexusmods.com/skyrim/mods/37900).'
          - lang: es
            text: 'Requiere: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) or [CBBE](http://www.nexusmods.com/skyrim/mods/2666) or [UNP Blessed Body (UNPB)](http://www.nexusmods.com/skyrim/mods/37900).'
          - lang: ja
            text: '要: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) か [CBBE](http://www.nexusmods.com/skyrim/mods/2666) か [UNP Blessed Body (UNPB)](http://www.nexusmods.com/skyrim/mods/37900)'
          - lang: ru
            text: 'Требуется: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) или [CBBE](http://www.nexusmods.com/skyrim/mods/2666) или [UNP Blessed Body (UNPB)](http://www.nexusmods.com/skyrim/mods/37900).'

  - name: 'NewmillerShoesUNP.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Be sure this is the correct version of this esp for whichever body type you have installed. The esp name is NOT different for each body type.'
          - lang: de
            text: 'Stellen Sie sicher, dass dies die richtige Version dieser esp ist, abhängig davon, welchen Körpertyp Sie installiert haben. Der esp Name ist NICHT für jeden Körpertyp unterschiedlich.'
          - lang: ja
            text: 'このEspは必ずインストールした体型Modとマッチするバージョンのものを使用してください。Espの名前はそれぞれの体型用でまったく同じです。'
          - lang: ru
            text: 'Убедитесь, что используете корректную версию для установленного у вас реплейсера тела, так как esp-файл одинаков для обеих версий.'
      - type: say
        content:
          - lang: en
            text: 'Requires: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) or [CBBE](http://www.nexusmods.com/skyrim/mods/2666) or [UNP Blessed Body (UNPB)](http://www.nexusmods.com/skyrim/mods/37900).'
          - lang: de
            text: 'Benötigt: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) oder [CBBE](http://www.nexusmods.com/skyrim/mods/2666) oder [UNP Blessed Body (UNPB)](http://www.nexusmods.com/skyrim/mods/37900).'
          - lang: es
            text: 'Requiere: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) or [CBBE](http://www.nexusmods.com/skyrim/mods/2666) or [UNP Blessed Body (UNPB)](http://www.nexusmods.com/skyrim/mods/37900).'
          - lang: ja
            text: '要: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) か [CBBE](http://www.nexusmods.com/skyrim/mods/2666) か [UNP Blessed Body (UNPB)](http://www.nexusmods.com/skyrim/mods/37900)'
          - lang: ru
            text: 'Требуется: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) или [CBBE](http://www.nexusmods.com/skyrim/mods/2666) или [UNP Blessed Body (UNPB)](http://www.nexusmods.com/skyrim/mods/37900).'

  - name: 'Lia.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Be sure you have the correct body mod for the esp. [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) or [CBBE](http://www.nexusmods.com/skyrim/mods/2666).'
          - lang: de
            text: 'Stellen Sie sicher, dass Sie den richtigen Körper Mod für die esp haben. [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) oder [CBBE](http://www.nexusmods.com/skyrim/mods/2666).'
          - lang: ja
            text: '必ず[DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709)か[CBBE](http://www.nexusmods.com/skyrim/mods/2666)のうち、インストールされている体型Modと同じバージョンのEspを使用してください。.'
          - lang: ru
            text: 'Убедитесь, что используете корректный реплейсер тел для этого esp. [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) или [CBBE](http://www.nexusmods.com/skyrim/mods/2666).'

  - name: 'iLoveLydia.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This mod will conflict with any female body altering mods.'
          - lang: de
            text: 'Diese Mod steht in Konflikt mit allen Modifikationen, die den weiblichen Körper verändern.'
          - lang: ja
            text: 'このModは女性の体型を改変するModと競合します。'
          - lang: ru
            text: 'Этот мод может конфликтовать с любыми реплейсерами женских тел.'

  - name: 'bouncy_bodices.*\.esp'
    msg:
      - <<: *useOnlyOneX
        condition: 'many("bouncy_bodices.*\.esp")'
        subs: [ 'bouncy_bodices .esp file' ]
      - type: say
        content:
          - lang: en
            text: 'Be sure you have the correct body replacer installed for this esp.'
          - lang: de
            text: 'Stellen Sie sicher, dass Sie den richtigen Körper Ersetzer für diese esp installiert haben.'
          - lang: ja
            text: 'このEspを使用するときは適切な体型変更Modをインストールしてください。'
          - lang: ru
            text: 'Убедитесь, что для этого esp у вас установлена корректная версия реплейсера тел.'

  - name: 'DemonHunterArmor.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Be sure you have the correct version for the body type installed: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) or [CBBE](http://www.nexusmods.com/skyrim/mods/2666)'
          - lang: de
            text: 'Stellen Sie sicher, dass Sie die richtige Version für den Körpertyp installiert haben: [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) oder [CBBE](http://www.nexusmods.com/skyrim/mods/2666)'
          - lang: ja
            text: '必ずインストールされている体型Mod（[DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709)か[CBBE](http://www.nexusmods.com/skyrim/mods/2666)）とマッチするバージョンを使用してください。'
          - lang: ru
            text: 'Убедитесь что у вас установлена корректная версия типа тел: [DIMONIZED женское тело UNP](http://www.nexusmods.com/skyrim/mods/6709) или [женское тело CBBE](http://www.nexusmods.com/skyrim/mods/2666).'

  - name: 'MorSit.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Be sure to use the correct esp for [CBBE](http://www.nexusmods.com/skyrim/mods/2666) | [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709)'
          - lang: de
            text: 'Achten Sie darauf, die richtige esp für [CBBE](http://www.nexusmods.com/skyrim/mods/2666) | [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) zu verwenden.'
          - lang: ja
            text: '必ず[CBBE](http://www.nexusmods.com/skyrim/mods/2666)か[DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709)用のうちの適切なEspを使用するようにしてください。'
          - lang: ru
            text: 'Убедидесь, что используете правильный esp для [CBBE](http://www.nexusmods.com/skyrim/mods/2666) или [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709)'

  - name: 'SeraphineHuntedArmor.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Be sure you have the correct body mod for the esp. [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) or [CBBE](http://www.nexusmods.com/skyrim/mods/2666).'
          - lang: de
            text: 'Stellen Sie sicher, dass Sie den richtigen Körper Mod für die esp haben. [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) oder [CBBE](http://www.nexusmods.com/skyrim/mods/2666).'
          - lang: ja
            text: '必ず[DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709)か[CBBE](http://www.nexusmods.com/skyrim/mods/2666)のうち、インストールされている体型Modと同じバージョンのEspを使用してください。.'
          - lang: ru
            text: 'Убедитесь, что используете корректный реплейсер тел для этого esp. [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) или [CBBE](http://www.nexusmods.com/skyrim/mods/2666).'

  - name: 'FM - UNP Merchants.esp'
    msg:
      - type: warn
        condition: 'version("FM - UNP Merchants.esp", "4.0", <)'
        content:
          - lang: en
            text: 'The latest version (v4.0 and higher) of this mod is completely standalone now and has it''s own editor IDs, form IDs, folder structure and can be installed and used alongside any of the original mods it contains.'
          - lang: de
            text: 'Die neueste Version (v4.0 und höher) dieser Mod ist jetzt völlig eigenständig und verfügt über eigene Editor-IDs, Form-IDs und Ordnerstruktur. Sie kann zusammen mit den enthaltenen Original-Mods installiert und verwendet werden.'
          - lang: ja
            text: '最新版（v4.0以降）は完全にスタンドアローン化し、独自のEditor IDs、form ID、フォルダ構造を有しています。そのためオリジナルのModと別々にインストールし、同時に使用することができます。'

  - name: 'Companion_Crea.esp'
    msg:
      - *requiresCBBEorUNP
      - type: say
        content:
          - lang: en
            text: 'Be sure you have the correct esp for the body type installed.'
          - lang: de
            text: 'Stellen Sie sicher, dass Sie die richtige esp für den Körpertyp installiert haben.'
          - lang: ja
            text: '必ずインストールされている体型に対応するEspを使用してください。'
          - lang: ru
            text: 'Убедитесь, что вы используете правильный esp, для соответствующего типа тела'

  - name: 'Companion_Lese.esp'
    msg:
      - *requiresCBBEorUNP
      - type: say
        content:
          - lang: en
            text: 'Be sure you have the correct esp for the body type installed.'
          - lang: de
            text: 'Stellen Sie sicher, dass Sie die richtige esp für den Körpertyp installiert haben.'
          - lang: ja
            text: '必ずインストールされている体型に対応するEspを使用してください。'
          - lang: ru
            text: 'Убедитесь, что вы используете правильный esp, для соответствующего типа тела'

  - name: 'Illia.esp'
    msg:
      - <<: *corrupt
        condition: 'checksum("Illdi.esp",B941754D)'
      - type: say
        content:
          - lang: en
            text: 'Be sure you have the correct body mod for the esp. [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) or [CBBE](http://www.nexusmods.com/skyrim/mods/2666).'
          - lang: de
            text: 'Stellen Sie sicher, dass Sie den richtigen Körper Mod für die esp haben. [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) oder [CBBE](http://www.nexusmods.com/skyrim/mods/2666).'
          - lang: ja
            text: '必ず[DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709)か[CBBE](http://www.nexusmods.com/skyrim/mods/2666)のうち、インストールされている体型Modと同じバージョンのEspを使用してください。.'
          - lang: ru
            text: 'Убедитесь, что используете корректный реплейсер тел для этого esp. [DIMONIZED UNP](http://www.nexusmods.com/skyrim/mods/6709) или [CBBE](http://www.nexusmods.com/skyrim/mods/2666).'
```

</details>
