### ISSUE TITLE
Reevaluate unaliased messages - esm

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrim#457]
Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
No current suggestion.
```

---

# Plugins reevaluated:
- [x] Bandit Raid.esp
- [x] SuccubusFollower.esp
- [x] Succubus Summoning.esp
- [x] UDO.esm
- [x] UDOchestless.esp
- [x] whiterunppl1.esm
- [x] LB_MuchAdoSnowElves.esm

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'UDO.esm'
    msg:
      - *obsolete
      - type: say
        content:
          - lang: en
            text: 'UDO.esm is mis-named. It is NOT an esm file.'
          - lang: de
            text: 'UDO.esm ist falsch benannt. Es ist KEINE esm Datei.'
          - lang: ja
            text: 'UDO.esmのファイル名が間違っています。このファイルはEsmファイルではありません。'
          - lang: ru
            text: 'UDO.esm неверно назван. Это не esm-файл.'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x23a1b8f9
        udr: 3835
        nav: 1

  - name: 'UDOchestless.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'UDOChestless.esp does not have Skyrim.esm as a master file.  Most likely it will create duplicates of everything it is supposed to modify.'
          - lang: de
            text: 'UDOChestless.esp hat Skyrim.esm nicht als Masterdatei. Höchstwahrscheinlich werden Duplikate von allem erstellt, was geändert werden soll.'
          - lang: ja
            text: 'UDOChestless.espはSkyrim.esmをマスターファイルとしていません。変更だけで終わるはずの箇所が複製されてしまう可能性が高いでしょう。'
          - lang: ru
            text: 'UDOChestless.esp не имеет Skyrim.esm в мастерфайлах.  Наиболее вероятно будут созданны дубликаты всего, что было модифицировано.'

  - name: 'Bandit Raid.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'This is actually an esm released as an esp file.'
          - lang: de
            text: 'Dies ist eine esm Datei, die als esp Datei veröffentlicht wurde.'
          - lang: es
            text: 'Archivo esm distrubuido como esp.'
          - lang: ja
            text: 'このEspファイルは実際にはEsmファイルとして公開されています。'
          - lang: ru
            text: 'На самом деле это esm-файл, выпущенный как esp.'

  - name: 'SuccubusFollower.esp'
    inc: [ 'Succubus Summoning.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'This is a false esm file.'
          - lang: de
            text: 'Dies ist eine falsche esm Datei.'
          - lang: es
            text: 'Archivo esm distrubuido como esp.'
          - lang: ja
            text: 'Esmファイルの間違いです。'
          - lang: ru
            text: 'На самом деле это esm-файл, выпущенный как esp.'

  - name: 'Succubus Summoning.esp'
    inc: [ 'SuccubusFollower.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'This is a false esm file.'
          - lang: de
            text: 'Dies ist eine falsche esm Datei.'
          - lang: es
            text: 'Archivo esm distrubuido como esp.'
          - lang: ja
            text: 'Esmファイルの間違いです。'
          - lang: ru
            text: 'На самом деле это esm-файл, выпущенный как esp.'

  - name: 'whiterunppl1.esm'
    msg:
      - type: say
        content:
          - lang: en
            text: 'This is NOT a true esm file. It is mis-named.'
          - lang: de
            text: 'Dies ist keine echte esm Datei. Sie ist falsch benannt.'
          - lang: ja
            text: 'このファイルは実際にはEsmファイルではありません。ファイル名の付け間違いです。'
          - lang: ru
            text: 'Это не настоящий esm-файл. Неверно назван.'

  - name: 'LB_MuchAdoSnowElves.esm'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This is the wrong esm for LB_MuchAdoSnowElves_WeaponsOnly.esp'
          - lang: de
            text: 'Dies ist die falsche esm für LB_MuchAdoSnowElves_WeaponsOnly.esp.'
          - lang: ja
            text: 'LB_MuchAdoSnowElves_WeaponsOnly.esp用のEsmとは異なります。'
        condition: 'file("LB_MuchAdoSnowElves_WeaponsOnly.esp") and checksum("LB_MuchAdoSnowElves.esm",9E22BEF7)'
```

</details>
