### ISSUE TITLE
Reevaluate unaliased messages - Translation

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrim#458]
Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &languageX
    type: say
    content:
      - lang: en
        text: 'Language: %1%'
```

---

# Plugins reevaluated:
- [x] Manoir des chutes du Dragon.esp
- [x] Hebrock_Der Schatten von Meresis.esp
- [x] AmazingFollowerTweaks.esp

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'Manoir des chutes du Dragon.esp'
    msg:
      - type: error
        content:
          - lang: en
            text: 'French translation of Dragon Falls Manor.esp.'
          - lang: de
            text: 'Französische Übersetzung von Dragon Falls Manor.esp.'
          - lang: ja
            text: 'Dragon Falls Manor.espのフランス語版です。'
        condition: 'file("Dragon Falls Manor.esp")'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x2590076
        itm: 15
        udr: 19

  - name: 'Hebrock_Der Schatten von Meresis.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/25872' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'An English translation of this mod [is now available here](http://www.nexusmods.com/skyrim/mods/36843)'
          - lang: de
            text: 'Eine englische Übersetzung dieser Mod [ist jetzt hier verfügbar](http://www.nexusmods.com/skyrim/mods/36843).'
        condition: 'checksum("Hebrock_Der Schatten von Meresis.esp",49083650)'
      - type: say
        content:
          - lang: en
            text: 'The English version has been renamed starting from version 1.1.2.'
          - lang: de
            text: 'Die Englische Version wurde unbenannt, wirksam ab Version 1.1.2.'
        condition: 'checksum("Hebrock_Der Schatten von Meresis.esp",61DCB4E0)'
    dirty:
      - <<: *reqManualFix
        crc: 0x49083650
        util: '[TES5Edit v4.0.2f](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 103
        nav: 21
      - <<: *reqManualFix
        crc: 0x74C44958
        util: '[TES5Edit v4.0.2f](https://www.nexusmods.com/skyrim/mods/25859)'
        nav: 21

  - name: 'AmazingFollowerTweaks.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'German version'
          - lang: de
            text: 'Deutsche Version'
          - lang: ja
            text: 'ドイツ語版です。'
        condition: 'checksum("AmazingFollowerTweaks.esp",1482CEEC)'
    after: [ 'Inigo.esp' ]
    dirty:
      - <<: *quickClean
        crc: 0xD6C72A3C
        util: '[TES5Edit v4.0.2f](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 7
```

</details>
