### ISSUE TITLE
Reevaluate unaliased messages - In-Compatible

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrim#459]
Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &compatIssuesWithX
    type: say
    content:
      - lang: en
        text: 'This plugin has compatibility issues with %1%. For more information, read this mod''s compatibility notes.'
```

```yaml
  - &compatNotes
    type: say
    content:
      - lang: en
        text: 'It is recommended that you read this mod''s [Compatibility Notes](%1%).'
```

---

# Plugins reevaluated:
- [x] Sovngarde - completed main quest.esp
- [x] SkyJubs_Invisible_Helmets_Ger_Main_OnlyFullHelmets.esp
- [x] Imp''s More Complex Needs.esp
- [x] RCRN (Classic|Legacy|Pure) - Hybrid Shaders\\.esp
- [x] Whiterun Trees 1.1.esp

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'RCRN (Classic|Legacy|Pure) - Hybrid Shaders\.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: Original FXAA Post Process Injector and Realistic Lighting Without Post-Processing'
          - lang: de
            text: 'Inkompatibel mit: Original FXAA Post Process Injector und Realistic Lighting Without Post-Processing'
          - lang: es
            text: 'Incompatible con: FXAA Post Process Injector original y Realistic Lighting Without Post-Processing'
          - lang: ja
            text: '競合: Original FXAA Post Process InjectorおよびRealistic Lighting Without Post-Processing'
          - lang: ru
            text: 'Несовместим с: Оригинальный FXAA Post Process Injector и Realistic Lighting Without Post-Processing'

  - name: 'Sovngarde - completed main quest.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'This mod is not compatible with the last quest in the Main Quest chain. Either disable the .esp before you do it or wait until you complete the main quest.'
          - lang: de
            text: 'Diese Mod ist nicht kompatibel mit der letzten Quest in der Hauptquest-Abfolge. Deaktivieren Sie entweder die .esp, bevor Sie sie spielen, oder warten Sie, bis Sie die Hauptquest abgeschlossen haben.'
          - lang: ja
            text: 'このModはメインクエストの最終パートとは互換性がありません。最終パートに入る前にEspを無効にするか、メインクエストを終えるまで導入しないでください。'
          - lang: ru
            text: 'Этот мод не совместим с последним квестом в основной цепочке квестов. Либо отключите .esp, прежде чем сделать это, либо дождитесь, пока вы не завершите главный квест.'

  - name: 'SkyJubs_Invisible_Helmets_Ger_Main_OnlyFullHelmets.esp'
    inc:
      - 'SkyJubs_Invisible_Helmets_Eng_Main.esp'
      - 'SkyJubs_Invisible_Helmets_Ger_Main_AllHeaddress.esp'
    msg:
      # huge number of incompatible plugins, so this msg is likely better than inc
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: SkyJubs_Invisible_Helmets_Ger_ModKit_*.esp'
          - lang: de
            text: 'Inkompatibel mit: SkyJubs_Invisible_Helmets_Ger_ModKit_*.esp'
          - lang: ja
            text: '競合: SkyJubs_Invisible_Helmets_Ger_ModKit_*.esp'
        condition: 'file("SkyJubs_Invisible_Helmets_Ger_ModKit_.+\.esp")'

  - name: 'Imp''s More Complex Needs.esp'
    inc: [ 'Imp''s More Complex Needs.esm' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'It is recommended that you unsubscribe from and delete this mod, then install the [SkyrimNexus version](http://www.nexusmods.com/skyrim/mods/10639) for more compatibility with other mods.'
          - lang: de
            text: 'Es wird empfohlen, dass Sie diese Mod deabbonieren und löschen und dann die [SkyrimNexus-Version](http://www.nexusmods.com/skyrim/mods/10639) installieren, um die Kompatibilität mit anderen Mods zu verbessern.'
          - lang: ja
            text: 'サブスクライブを解除してModそのものを削除し、他のModとの互換性を高めるために[SkyrimNexus版](http://www.nexusmods.com/skyrim/mods/10639)をインストールすることをお勧めします。'
        condition: 'checksum("imp''s more complex needs.esp",DAADC533) or checksum("imp''s more complex needs.esp",59466F1E)'
    clean:
      - crc: 0x79B1B51C
        util: 'TES5Edit v4.0.2f'

  - name: 'Whiterun Trees 1.1.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Different mod with same name. Probably incompatible.'
          - lang: de
            text: 'Unterschiedliche Mod mit gleichem Namen. Wahrscheinlich nicht kompatibel.'
          - lang: ja
            text: '同名のModとは異なります。おそらく両立できません。'
        condition: 'checksum("Whiterun Trees.esp",D2995274)'
```

</details>
