### ISSUE TITLE
Reevaluate unaliased messages - Use

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrim#460]
Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &useInstead
    type: warn
    content:
      - lang: en
        text: 'Use %1% instead.'
```

---

# Plugins reevaluated:
- [x] valkiirs_tastier_food.esp (deleted [here](https://steamcommunity.com/sharedfiles/filedetails/?id=12402) & [here](https://steamcommunity.com/sharedfiles/filedetails/?id=107616193))
- [x] [vanillaarcheryimproved.esp](https://steamcommunity.com/sharedfiles/filedetails/?id=71452193)
- [x] VanillaMonsterLoot.esp
- [x] RiverwoodEnhancedPlugin.esp
- [x] tos_oakwood.esp
- [x] TownsAndCitiesEnhanced.esp
- [x] [KTNUlfric.esp](https://www.nexusmods.com/skyrim/mods/16828)
- [x] RND_BabettesFeast-Patch.esp
- [x] RND_DestructibleBottles-Patch.esp
- [x] RND_NCVE-Patch.esp (unsourceable)
- [x] RND_RWL-Patch.esp (unsourceable)
- [x] [RND_RWS-Patch.esp](https://www.nexusmods.com/skyrim/mods/78785/)
- [x] [SpecializedFollowers.esp](https://www.nexusmods.com/skyrim/mods/7245/)
- [x] RealisticWaterTextures.esp (presumably [deleted](https://www.nexusmods.com/skyrim/mods/711))
- [x] RWTT - Get Wet.esp (unsourceable)
- [x] GuardAnimations.esp
- [x] Remove Interior Fog V2 - Skyrim.esp
- [x] Remove Interior Fog V2 - Full Version.esp
- [x] Skyrim Immersive Creatures.esp
- [x] Skyrim Immersive Creatures - DLC2.esp
- [x] Skyrim Scaling Stopper - Misc Edits.esp (presumably [no longer available](https://www.nexusmods.com/skyrim/mods/9857))
- [x] [`WolfsRecettes.+\.esp`](https://www.nexusmods.com/skyrim/mods/1368/)
- [x] CWND-Basic.esp
- [x] [CAS.esp](https://www.nexusmods.com/skyrim/mods/21015/)
- [x] `SkyRealism - Simple Save System.+\.esp`
- [x] `Smithing Perks Overhaul( - Balanced)?\.esp`
- [x] Smithing Perks Overhaul.esp
- [x] [`Complete Crafting Overhaul( - BS version)?\.esp`](https://www.nexusmods.com/skyrim/mods/8003/)
- [x] YASH.esp (presumably [no longer available](https://www.nexusmods.com/skyrim/mods/32562)
- [x] [`(ERSO 03 - )?(Soft)?(Super)?(Nightmare)?(Slighty| Slighty)?(Mighty| Mighty)? Dragons( Unleveled)?( v\.\d\.\d)?\.esp`](https://www.nexusmods.com/skyrim/mods/73222/)
- [x] `(ERSO 03.2 patch - )?(MD with )?DeadlyD( and)? DDiversified( Dawnguard)?( Unleveled)?\.esp` (presumably [no longer available](https://www.nexusmods.com/skyrim/mods/73222))

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'tos_oakwood.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'You need to use Heartfires version of Oakwood to work as intended with Hearthfires.'
          - lang: de
            text: 'Sie müssen die Heartfires Version von Oakwood verwenden, damit die Mod wie vorgesehen mit Hearthfires zusammen funktioniert.'
          - lang: ja
            text: 'Hearthfiresでも本来の動作をさせるにはHeartfiresバージョンのOakwoodを使用する必要があります。'
        condition: 'active("HearthFires.esm")'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x9ff8763e
        itm: 9
        udr: 3

  - name: 'VanillaMonsterLoot.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Use Dawnguard version - ImprovedMonsterLoot.esp'
          - lang: de
            text: 'Verwenden Sie die Dawnguard Version - ImprovedMonsterLoot.esp'
          - lang: ja
            text: 'DawnguardバージョンのImprovedMonsterLoot.espを使用してください。'
        condition: 'active("Dawnguard.esm")'
    tag: [ Relev ]

  - name: 'SkyRealism - Simple Save System.+\.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Only use one SkyRealism - Simple Save System*.esp.'
          - lang: de
            text: 'Verwenden Sie nur eine SkyRealism - Simple Save System*.esp.'
          - lang: es
            text: 'Utilizar solo un SkyRealism - Simple Save System*.esp.'
          - lang: ja
            text: 'SkyRealism - Simple Save System*.espは単体でのみ使用できます。'
          - lang: ru
            text: 'Используйте только один SkyRealism - Simple Save System*.esp.'

  - name: 'Smithing Perks Overhaul( - Balanced)?\.esp'
    inc: [ 'PerkUP-Smithing.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Does not contain unexpected (or out of order) records or TESVSnip truncation issues as found in other mods by various authors.  However, a newer esp fixed and cleaned with TES5Edit can be obtained here that may provide added stability. [Compatibility Patch](http://www.nexusmods.com/skyrim/mods/26230)'
          - lang: de
            text: 'Enthält keine unerwarteten (oder nicht ordnungsgemäßen) Datensätze oder TESVSnip Kürzungsprobleme, wie sie in anderen Mods von verschiedenen Autoren gefunden wurden. Eine neuere Version, die mit TES5Edit repariert und gereinigt wurde und zusätzliche Stabilität bietet, kann hier bezogen werden. [Kompatibilitätspatch] (http://www.nexusmods.com/skyrim/mods/26230)'
          - lang: ja
            text: '予期しない（または順番が狂った）レコード、または他の作者のModで見られたようなTESVSnipの切り捨て問題は存在しませんが、TES5Editで修正しクリーニングを行った新しいEspも入手可能です。こちらはより安定するでしょう。[Compatibility Patch](http://www.nexusmods.com/skyrim/mods/26230)'
          - lang: ru
            text: 'Не содержит неверных записей, как было найдено в других модах от разных авторов, однако новый esp, исправленный и очищенный в Tes5Edit вы можене найти [здесь](http://www.nexusmods.com/skyrim/mods/26230). Исправленный esp добавит больше стабильности. Если вы уже используете русифицированную-исправленную версию, то вам не о чем беспокоиться.'
        condition: 'not checksum("Smithing Perks Overhaul.esp",92158BE3) and not checksum("Smithing Perks Overhaul - Balanced.esp",80AAE7FF)'

  - name: 'Smithing Perks Overhaul.esp'
    inc: [ 'Smithing Perks Overhaul - Balanced.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Use Smithing Perks Overhaul - Balanced.esp with Complete Crafting Overhaul.'
          - lang: de
            text: 'Verwenden Sie Smithing Perks Overhaul - Balanced.esp mit Complete Crafting Overhaul.'
          - lang: es
            text: 'Usar Smithing Perks Overhaul - Balanced.esp como Complete Crafting Overhaul.'
          - lang: ja
            text: 'Complete Crafting OverhaulとはSmithing Perks Overhaul - Balanced.espを使用してください。'
          - lang: ru
            text: 'С модом Smithing Perks Overhaul - Balanced.esp используйте Complete Crafting Overhaul.'
        condition: 'file("Complete Crafting Overhaul.esp")'

  - name: 'valkiirs_tastier_food.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Use Hearthfires version to get changes made to Hearthfires food.'
          - lang: de
            text: 'Verwenden Sie die Hearthfires Version, um Änderungen am Essen von Hearthfires zu erhalten.'
          - lang: ja
            text: 'Hearthfiresの食べ物にも変更を加えるならHearthfiresバージョンを使用してください。'
        condition: 'active("HearthFires.esm")'

  - name: 'RND_NCVE-Patch.esp'
    after: [ '3DNPC.esp' ]
    msg:
      - type: error
        content:
          - lang: en
            text: 'Remove. Use RND_NCVE-FAMP.esp instead.'
          - lang: de
            text: 'Zu löschen. Verwenden Sie stattdessen RND_NCVE-FAMP.esp.'
          - lang: ja
            text: '削除し、RND_NCVE-FAMP.espを使用してください。'
          - lang: ru
            text: 'Удалите. Используйте RND_RWS-FAMP.esp вместо этого.'
        condition: 'file("PotionsBETA.esp")'

  - name: 'RND_RWL-Patch.esp'
    after: [ '3DNPC.esp' ]
    msg:
      - type: error
        content:
          - lang: en
            text: 'Remove. Use RND_RWL-FAMP.esp instead.'
          - lang: de
            text: 'Löschen. Verwenden Sie stattdessen RND_RWL-FAMP.esp.'
          - lang: ja
            text: '削除し、RND_RWL-FAMP.espを使用してください。'
          - lang: ru
            text: 'Удалите. Используйте RND_RWS-FAMP.esp вместо этого.'
        condition: 'file("PotionsBETA.esp")'

  - name: 'RealisticWaterTextures.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'DELETE. Use WATER.esp instead'
          - lang: de
            text: 'Löschen. Verwenden Sie stattdessen WATER.esp'
          - lang: es
            text: 'Borrar. Utilizar WATER.esp en lugar.'
          - lang: ja
            text: '削除してWATER.espを使用してください。'
          - lang: ru
            text: 'Удалите. Используйте WATER.esp вместо этого.'
        condition: 'file("WATER.esp")'
      - type: warn
        content:
          - lang: en
            text: 'Old. Use [WATER](http://www.nexusmods.com/skyrim/mods/13268) mod instead.'
          - lang: de
            text: 'Ist Veraltet. Verwenden Sie stattdessen die [WATER](http://www.nexusmods.com/skyrim/mods/13268) Mod.'
          - lang: es
            text: 'Obsoleto. Utilizar [WATER](http://www.nexusmods.com/skyrim/mods/13268) en lugar.'
          - lang: ja
            text: '古いファイルです。[WATER](http://www.nexusmods.com/skyrim/mods/13268)を使用してください。'
          - lang: ru
            text: 'Устарело. Используйте вместо этого мод [WATER](http://www.nexusmods.com/skyrim/mods/13268).'
        condition: 'file("WATER.esp")'

  - name: 'RWTT - Get Wet.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Originally for Realistic Water Textures and Terrain, may be obsolete.'
          - lang: de
            text: 'Ursprünglich für Realistic Water Textures and Terrain, kann hinfällig sein.'
          - lang: ja
            text: '本来はRealistic Water Textures and Terrain用のEspです。旧式のファイルかもしれません。'
          - lang: ru
            text: 'В основном реалистичные текстуры воды и земли, вероятно устарело.'

  - name: 'Skyrim Scaling Stopper - Misc Edits.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'If version 3+ is being used, Skyrim Monster Mod is required.'
          - lang: de
            text: 'Ab Version 3+ ist der Skyrim Monster Mod erforderlich.'
          - lang: es
            text: 'Skyrim Monster Mod es requerido si utilizas la versión 3+.'
          - lang: ja
            text: 'バージョン3以降ではSkyrim Monster Modが必要です。'
          - lang: ru
            text: 'Для версий 3 или выше требуется Skyrim Monster Mod.'
    tag:
      - Delev
      - Relev

  - name: 'CWND-Basic.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Does not work with Skyrim version 1.8.151.0.7 and beyond. Use the [Unofficial patches](http://modgames.net/load/247-1-0-13970) to fix.'
          - lang: de
            text: 'Funktioniert nicht mit Skyrim Version 1.8.151.0.7 und höher. Verwenden Sie die [Inoffiziellen Patches](http://modgames.net/load/247-1-0-13970).'
          - lang: ja
            text: 'バージョン1.8.151.0.7以降のSkyrimでは動作しません。[Unofficial patches](http://modgames.net/load/247-1-0-13970)で修正できます。'
          - lang: ru
            text: 'Не работает с версиями Скайрим 1.8.151.0.7 и выше. Используйте вместо этого альтернативную версию - CWND-UnofficialPatches.esp'
        condition: 'not file("CWND-UnofficialPatches.esp") and version("../TESV.exe","1.8.151.0.7",==)'

  - name: 'YASH.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If installing optional files, use either YASH.esp + YASH_AllOptionals.esp OR YASH.esp + one or more of the optional ESPs.'
          - lang: de
            text: 'Wenn Sie optionale Dateien installieren, verwenden Sie entweder YASH.esp + YASH_AllOptionals.esp ODER YASH.esp + eine oder mehrere der optionalen ESPs.'
          - lang: ja
            text: 'オプションファイルをインストールする場合、YASH.espとYASH_AllOptionals.espか、YASH.espと他のオプションファイルのどちらかの組み合わせで使用してください。'
          - lang: ru
            text: 'Если установлены опциональные файлы, используйте любой YASH.esp + YASH_AllOptionals.esp или YASH.esp + один или более опциональных ESP.'

  - name: '(ERSO 03.2 patch - )?(MD with )?DeadlyD( and)? DDiversified( Dawnguard)?( Unleveled)?\.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'ERSO 03.2 plugins are no longer recommended or supported by the mod author.'
          - lang: de
            text: 'ERSO 03.2 Plugins werden vom Mod Autor nicht mehr empfohlen oder unterstützt.'
          - lang: ja
            text: 'ERSO 03.2のプラグインは現在は製作者によってサポートされておらず、使用は推奨されません。'
          - lang: ru
            text: 'Плагины ERSO 03.2 больше не рекомендуются или поддерживаются автором.'

  - name: 'vanillaarcheryimproved.esp'
    msg:
      - type: error
        content:
          - lang: en
            text: 'Use vanillaarcheryimproveddawnguard.esp instead'
          - lang: de
            text: 'Verwenden Sie stattdessen vanillaarcheryimproveddawnguard.esp'
          - lang: ja
            text: 'vanillaarcheryimproveddawnguard.espを使用してください。'
          - lang: ru
            text: 'Используйте вместо этого vanillaarcheryimproveddawnguard.esp'
        condition: 'active("Dawnguard.esm") and not file("vanillaarcheryimproveddawnguard.esp")'

  - name: 'RiverwoodEnhancedPlugin.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/18952' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Use the [Lanterns of Skyrim and Towns and Villages Enhanced patch](http://www.nexusmods.com/skyrim/mods/27395) instead to have Lanterns of Skyrim work properly with Towns and Villages Enhanced - Riverwood.'
          - lang: de
            text: 'Verwenden Sie stattdessen den Patch [Lanterns of Skyrim and Towns and Villages Enhanced](http://www.nexusmods.com/skyrim/mods/27395), damit Lanterns of Skyrim ordnungsgemäß mit Towns and Villages Enhanced - Riverwood zusammen funktioniert.'
          - lang: ja
            text: 'Lanterns of SkyrimとTowns and Villages Enhanced - Riverwoodを正常に両立させるには[Lanterns of Skyrim and Towns and Villages Enhanced patch](http://www.nexusmods.com/skyrim/mods/27395)を代わりに使用する必要があります。'
        condition: 'file("Lanterns Of Skyrim - All In One - Main.esm")'
      - type: error
        content:
          - lang: en
            text: 'Remove. LoS and RE patch.esp is designed as a replacement for RiverwoodEnhancedPlugin.esp, not as an add-on.'
          - lang: de
            text: 'Zu löschen. LoS and RE patch.esp wurde als Ersatz für RiverwoodEnhancedPlugin.esp entwickelt und nicht als Add-On.'
          - lang: ja
            text: '削除してください。LoS and RE patch.espはRiverwoodEnhancedPlugin.espを置き換えるように作られています。アドオンではありません。'
        condition: 'file("LoS and RE patch.esp")'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x5b3c0e5a
        itm: 4
        udr: 5

  - name: 'TownsAndCitiesEnhanced.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/17406' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Use the [Lanterns of Skyrim and Towns and Villages Enhanced patch](http://www.nexusmods.com/skyrim/mods/27395) instead to have Lanterns of Skyrim work properly with Towns And Cities Enhanced.'
          - lang: de
            text: 'Verwenden Sie stattdessen den Patch [Lanterns of Skyrim and Towns and Villages Enhanced](http://www.nexusmods.com/skyrim/mods/27395), damit Lanterns of Skyrim ordnungsgemäß mit Towns And Cities Enhanced zusammen funktioniert.'
          - lang: ja
            text: 'Lanterns of SkyrimとTowns And Cities Enhancedを正常に両立させるには[Lanterns of Skyrim and Towns and Villages Enhanced patch](http://www.nexusmods.com/skyrim/mods/27395)を代わりに使用する必要があります。'
        condition: 'file("Lanterns Of Skyrim - All In One - Main.esm")'
      - type: error
        content:
          - lang: en
            text: 'Remove. L0S and TaVE patch.esp is designed as a replacement for TownsAndCitiesEnhanced.esp, not as an add-on.'
          - lang: de
            text: 'Zu löschen. L0S und TaVE patch.esp wurde als Ersatz für TownsAndCitiesEnhanced.esp entwickelt, nicht als Add-On.'
          - lang: ja
            text: '削除してください。L0S and TaVE patch.espはTownsAndCitiesEnhanced.espを置き換えるように作られています。アドオンではありません。'
        condition: 'file("L0S and TaVE patch.esp")'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xa37760e6
        itm: 18

  - name: 'KTNUlfric.esp'
    msg:
      - type: error
        content:
          - lang: en
            text: 'Use UFO version of KTNUlfric.esp'
          - lang: de
            text: 'Verwenden Sie die UFO Version von KTNUlfric.esp'
          - lang: ja
            text: 'KTNUlfric.espのUFOバージョンを使用してください。'
        condition: 'checksum("KTNUlfric.esp",8CF90F55) and file("UFO - Ultimate Follower Overhaul.esp")'
      - type: error
        content:
          - lang: en
            text: 'Use UFO version of KTNUlfric.esp'
          - lang: de
            text: 'Verwenden Sie die UFO Version von KTNUlfric.esp'
          - lang: ja
            text: 'KTNUlfric.espのUFOバージョンを使用してください。'
        condition: 'checksum("KTNUlfric.esp",35CB3586) and not file("UFO - Ultimate Follower Overhaul.esp")'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x35cb3586
        itm: 15
      - <<: *dirtyPlugin
        crc: 0x8cf90f55
        itm: 18

  - name: 'RND_BabettesFeast-Patch.esp'
    after: [ '3DNPC.esp' ]
    msg:
      - type: error
        content:
          - lang: en
            text: 'Remove. Use RND_BabettesFeast-FAMP.esp instead.'
          - lang: de
            text: 'Zu löschen. Verwenden Sie stattdessen RND_BabettesFeast-FAMP.esp.'
          - lang: ja
            text: '削除し、RND_BabettesFeast-FAMP.espを使用してください。'
          - lang: ru
            text: 'Удалите. Используйте RND_RWS-FAMP.esp вместо этого.'
        condition: 'file("PotionsBETA.esp")'

  - name: 'RND_DestructibleBottles-Patch.esp'
    after: [ '3DNPC.esp' ]
    msg:
      - type: error
        content:
          - lang: en
            text: 'Remove. Use RND_DestructibleBottles-FAMP.esp instead.'
          - lang: de
            text: 'Zu löschen. Verwenden Sie stattdessen RND_DestructibleBottles-FAMP.esp.'
          - lang: ja
            text: '削除し、RND_DestructibleBottles-FAMP.espを使用してください。'
          - lang: ru
            text: 'Удалите. Используйте RND_RWS-FAMP.esp вместо этого.'
        condition: 'file("PotionsBETA.esp")'

  - name: 'RND_RWS-Patch.esp'
    after: [ '3DNPC.esp' ]
    msg:
      - type: error
        content:
          - lang: en
            text: 'Remove. Use RND_RWS-FAMP.esp instead.'
          - lang: de
            text: 'Zu löschen. Verwenden Sie stattdessen RND_RWS-FAMP.esp.'
          - lang: ja
            text: '削除し、RND_RWS-FAMP.espを使用してください。'
          - lang: ru
            text: 'Удалите. Используйте RND_RWS-FAMP.esp вместо этого.'
        condition: 'file("PotionsBETA.esp")'

  - name: 'SpecializedFollowers.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Delete. Use Better Followers - S*.esp instead.'
          - lang: de
            text: 'Zu löschen. Verwenden Sie stattdessen Better Followers - S*.esp.'
          - lang: ja
            text: '削除してBetter Followers - S*.espを使用してください。'
          - lang: ru
            text: 'Удалите. Используйте вместо этого Better Followers - S*.esp.'
        condition: 'file("Better Followers - .+\.esp")'

  - name: 'GuardAnimations.esp'
    url: [ 'http://www.nexusmods.com/skyrim/mods/52326' ]
    msg:
      - type: warn
        condition: 'active("Guard Dialogue Overhaul.esp")'
        content:
          - lang: en
            text: 'Guard Dialogue Overhaul detected. Use the Guard Dialogue Overhaul version to have both mods work as intended.'
          - lang: de
            text: 'Guard Dialogue Overhaul erkannt. Verwenden Sie die Guard Dialogue Overhaul Version, damit beide Mods wie vorgesehen funktionieren.'
          - lang: ja
            text: 'Guard Dialogue Overhaulが見つかりました。本来の動作をさせるにはGuard Dialogue Overhaulバージョンを使用する必要があります。'

  - name: 'Remove Interior Fog V2 - Skyrim.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/29253' ]
    inc: [ 'RemoveAmbientInteriorFog.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Use Remove Interior Fog V2 - Dawnguard.esp in addition to include Dawnguard locations.'
          - lang: de
            text: 'Verwenden Sie ebenfalls Remove Interior Fog V2 - Dawnguard.esp, um zusätzlich Dawnguard-Standorte einzuschließen.'
          - lang: ja
            text: 'Dawnguardのロケーションに対応させるためにRemove Interior Fog V2 - Dawnguard.espを使用してください。'
        condition: 'file("Dawnguard.esm")'
      - type: say
        content:
          - lang: en
            text: 'Use Remove Interior Fog V2 - Hearthfire.esp in addition to include Hearthfires locations.'
          - lang: de
            text: 'Verwenden Sie ebenfalls Remove Interior Fog V2 - Hearthfire.esp, um zusätzlich Hearthfire-Standorte einzuschließen.'
          - lang: ja
            text: 'Hearthfiresのロケーションに対応させるためにRemove Interior Fog V2 - Hearthfire.espを使用してください。'
        condition: 'file("HearthFires.esm")'

  - name: 'Remove Interior Fog V2 - Full Version.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/29253' ]
    msg:
      - type: error
        content:
          - lang: en
            text: 'Do not use the modular versions of Remove Interior Fog V2 with the Full version.'
          - lang: de
            text: 'Verwenden Sie nicht die modularen Versionen von Remove Interior Fog V2 mit der Vollversion.'
          - lang: ja
            text: 'Full版のRemove Interior Fog V2を使用する場合は個別インストール版を使用しないでください。'
        condition: 'file("Remove Interior Fog V2 - (Skyrim|Dawnguard|Hearthfire)?\.esp")'
    dirty:
      # v1.3
      - <<: *quickClean
        crc: 0x4FD63CD3
        util: '[TES5Edit v4.0.2j](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 3

  - name: 'Skyrim Immersive Creatures.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/24913' ]
    after:
      - 'Sleeping Dangers - Sands of Time.esp'
      - 'SleepingDangers-SandsofTime.esp'
    inc:
      - name: 'Skyrim Immersive Creatures.esm'
        condition: 'not checksum("Skyrim Immersive Creatures.esp",2EEAD88A)'
    msg:
      - type: say
        content:
          - lang: en
            text: 'This is the Lore-Friendly version by jackstarr. Do not use the original esp or esm by lifestorock.'
          - lang: de
            text: 'Dies ist die Lore-Freundliche-Version von jackstarr. Verwenden Sie nicht die Original esp oder esm von lifestorock.'
          - lang: ja
            text: 'このEspはjackstarr氏によるロアフレンドリーバージョンです。lifestorock氏によるオリジナル版のEspもしくはEsmは使用しないでください。'
        condition: 'checksum("Skyrim Immersive Creatures.esp",2EEAD88A)'
      - <<: *patch3rdParty_Requiem_MRP
        condition: 'active("Requiem.esp") and not active("Requiem - Immersive Creatures.esp")'
    tag:
      - Delev
      - Relev
    clean:
      - crc: 0xBA4FDA63
        util: 'TES5Edit v4.0.2f'

  - name: 'Skyrim Immersive Creatures - DLC2.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/24913' ]
    msg:
      - type: error
        content:
          - lang: en
            text: 'This addon is for use with Skyrim Immersive Creatures.esm, not Skyrim Immersive Creatures.esp'
          - lang: de
            text: 'Dieses Addon ist für die Verwendung mit Skyrim Immersive Creatures.esm vorgesehen, nicht mit Skyrim Immersive Creatures.esp.'
          - lang: ja
            text: 'Skyrim Immersive Creatures.esm用のアドオンです。Skyrim Immersive Creatures.esp用ではありません。'
        condition: 'checksum("Skyrim Immersive Creatures - DLC2.esp",C64CF88A) and not active("Skyrim Immersive Creatures.esm")'
    tag:
      - Delev
      - Relev
    clean:
      - crc: 0x2C158B9F
        util: 'TES5Edit v4.0.2f'

  - name: 'WolfsRecettes.+\.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Use Wolfs_*_Recipes esps or WolfsRecettes* esps, not both.'
          - lang: de
            text: 'Benutzen Sie Wolfs_*_Recipes esps oder WolfsRecettes* esps, nicht beide.'
          - lang: es
            text: 'Usar Wolfs_*_Recipes esps o WolfsRecettes* esps, no ambos.'
          - lang: ja
            text: 'Wolfs_*_Recipes espかWolfsRecettes* espのどちらかを使用してください。'
          - lang: ru
            text: 'Используйте Wolfs_*_Recipes esps или WolfsRecettes* esps, не не вместе.'
        condition: 'file("Wolfs_.+_Recipes\.esp") and file("WolfsRecettes.+\.esp")'

  - name: 'CAS.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Only use the save features of either "CAS" or "kuertee''s auto-save and time".'
          - lang: de
            text: 'Verwenden Sie nur die Speicherfunktionen von "CAS" oder "kuertee''s auto-save and time".'
          - lang: es
            text: 'Utilizar únicamente las funciones de guardar de "CAS" o "kuertee''s auto-save and time".'
          - lang: ja
            text: 'セーブ機能は「CAS」か「kuertee''s auto-save and time」のどちらかの機能のみ利用できます。'
          - lang: ru
            text: 'Используйте функцию сохранения только  из одного мода: из "CAS" или "kuertee''s auto-save and time".'
        condition: 'file("kuerteeAutoSaveAndTime.esp")'

  - name: 'Complete Crafting Overhaul( - BS version)?\.esp'
    inc: [ 'Smithing Perks Overhaul.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Does not contain unexpected (or out of order) records or TESVSnip truncation issues as found in other mods by various authors.  However, a newer esp fixed and cleaned with TES5Edit can be obtained here that may provide added stability. [Compatibility Patch](http://www.nexusmods.com/skyrim/mods/26230)'
          - lang: de
            text: 'Enthält keine unerwarteten (oder nicht ordnungsgemäßen) Datensätze oder TESVSnip Kürzungsprobleme, wie sie in anderen Mods von verschiedenen Autoren gefunden wurden. Eine neuere Version, die mit TES5Edit repariert und gereinigt wurde und zusätzliche Stabilität bietet, kann hier bezogen werden. [Kompatibilitätspatch] (http://www.nexusmods.com/skyrim/mods/26230)'
          - lang: ja
            text: '予期しない（または順番が狂った）レコード、または他の作者のModで見られたようなTESVSnipの切り捨て問題は存在しませんが、TES5Editで修正しクリーニングを行った新しいEspも入手可能です。こちらはより安定するでしょう。[Compatibility Patch](http://www.nexusmods.com/skyrim/mods/26230)'
          - lang: ru
            text: 'Не содержит неверных записей, как было найдено в других модах от разных авторов, однако новый esp, исправленный и очищенный в Tes5Edit вы можене найти [здесь](http://www.nexusmods.com/skyrim/mods/26230). Исправленный esp добавит больше стабильности. Если вы уже используете русифицированную-исправленную версию, то вам не о чем беспокоиться.'
        condition: 'not checksum("Complete Crafting Overhaul.esp",8534CD3C) and not checksum("Complete Crafting Overhaul - BS version.esp",193D9214)'
      - type: warn
        content:
          - lang: en
            text: 'Use only BS-version for Better Sorting.'
          - lang: de
            text: 'Verwenden Sie nur die BS-Version für Better Sorting.'
          - lang: ja
            text: 'Better SortingにはBS-versionを使用してください。'
          - lang: ru
            text: 'Для Better Sorting используйте только BS-версию.'
        condition: 'file("(Headbomb''s )?Better Sorting.*\.esp") and file("Complete Crafting Overhaul.esp")'
      - type: warn
        content:
          - lang: en
            text: 'Skyre mod is detected. Possible doubles in crafting menu'
          - lang: de
            text: 'Skyre Mod wird erkannt. Doppelte Einträge im Herstellungssmenü möglich.'
          - lang: ja
            text: 'Skyreが見つかりました。製作メニューが重複する可能性があります。'
          - lang: ru
            text: 'Обнаружен мод SkyRe. Возможны дубликаты в меню крафтинга.'
        condition: 'file("SkyRe_Main.esp") or file("SkyRe_Main_NoDawnguard.esp")'
      - type: say
        content:
          - lang: en
            text: 'Will conflict with mods that modify existing recipes.'
          - lang: de
            text: 'Wird im Konflikt mit Modifikationen stehen, die vorhandene Rezepte ändern.'
          - lang: ja
            text: '既存の製法を変更するModとは競合します。'
          - lang: ru
            text: 'Возможны конфликты с модами, модифицирующими существующие рецепты.'

  - name: '(ERSO 03 - )?(Soft)?(Super)?(Nightmare)?(Slighty| Slighty)?(Mighty| Mighty)? Dragons( Unleveled)?( v\.\d\.\d)?\.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Use the [compatibility patch](http://www.nexusmods.com/skyrim/mods/13423) for deadly dragons.'
          - lang: de
            text: 'Verwenden Sie den [Kompatibilitätspatch](http://www.nexusmods.com/skyrim/mods/13423) für Deadly Dragons.'
          - lang: ja
            text: '[compatibility patch](http://www.nexusmods.com/skyrim/mods/13423)にあるDeadly Dragons用の互換パッチを使用してください。'
          - lang: ru
            text: 'Используйте [патч совместимости](http://www.nexusmods.com/skyrim/mods/13423) для мода Deadly Dragons.'
        condition: 'file("DeadlyDragons(Hard|Normal|Hardcore)?( DV)?\.esp") and not file("MD with DeadlyD and DDiversified( Unleveled)?\.esp")'
    tag:
      - Delev
      - Relev
```

</details>
