### ISSUE TITLE
Fix Enhanced Soul Trap.esp's messages

### ISSUE THREAD

**Issue by Freso** [loot/skyrim#48]
Enhanced Soul Trap.esp currently has two contradicting messages, one having some conditions, the other not:

```
  - name: 'Enhanced Soul Trap.esp'
    msg:
      - type: say
        content: 'Use the Acquisitive Soul Gems compatible version.'
        condition: 'checksum("Enhanced Soul Trap.esp",B4803235) or checksum("Enhanced Soul Trap.esp",DF45FD75) or checksum("Enhanced Soul Trap.esp",C5F82F49)'
      - type: say
        content: 'Use the Acquisitive Soul Gems non-compatible version.'
        condition: ''
```

This should be cleaned up somehow.
