### ISSUE TITLE
Update RCRN

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrim#505]
[RCRN AE -- HDR Lighting and Weather Enhancement](https://www.nexusmods.com/skyrim/mods/1875)
[RCRN Plus - ENB](https://www.nexusmods.com/skyrim/mods/180)

Current masterlist data:
```yaml
  - name: 'RCRN (Classic|Legacy|Pure) - Hybrid Shaders\.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: Original FXAA Post Process Injector and Realistic Lighting Without Post-Processing'
          - lang: de
            text: 'Inkompatibel mit: Original FXAA Post Process Injector und Realistic Lighting Without Post-Processing'
          - lang: es
            text: 'Incompatible con: FXAA Post Process Injector original y Realistic Lighting Without Post-Processing'
          - lang: ja
            text: '競合: Original FXAA Post Process InjectorおよびRealistic Lighting Without Post-Processing'
          - lang: ru
            text: 'Несовместим с: Оригинальный FXAA Post Process Injector и Realistic Lighting Without Post-Processing'
  - name: 'rcrnShaders.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Make sure you have bEnableFileSelection=1 in SkyrimPrefs.ini under [Launcher].'
          - lang: de
            text: 'Stellen Sie sicher, dass bEnableFileSelection=1 in SkyrimPrefs.ini unter [Launcher] angegeben ist.'
          - lang: ja
            text: 'ランチャーから必ずSkyrimPrefs.iniのbEnableFileSelectionを=1にセットしてください。'
          - lang: ru
            text: 'Убедитесь, что строка bEnableFileSelection=1 в SkyrimPrefs.ini находитсся в секции [Launcher].'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x209fd1b5
        itm: 16
        udr: 3
  - name: 'rcrnPlus.esp'
  - name: 'RCRNvolumetric.esp'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x54176f89
        itm: 2
```

Also under https://github.com/loot/skyrim/issues/459 for the `msg` of the `RCRN (Classic|Legacy|Pure) - Hybrid Shaders\.esp` entry.
Also under https://github.com/loot/skyrim/issues/461 for the `msg` of the `rcrnShaders.esp` entry.
Also under https://github.com/loot/skyrim/issues/196 since `RCRNvolumetric.esp` was added by @v111v111 in [this commit](https://github.com/boss-developers/skyrim/commit/c1ade1dd1e568919924d2b37994a5325a23157f6).

RCRN is a mod that must be installed via `RCRN_AE_214.exe` and it will install *multiple* different versions of it's plugins, that also get installed as optional plugins in the Skyrim main folder.

___

```yaml
  - name: 'rcrnPlus.esp'
```
This is an entry without any data to it aside of it's name. It can be updated like this:
```yaml
  - name: 'rcrnPlus.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/180' ]
    dirty:
      - <<: *quickClean
        crc: 0x19390471
        util: '[TES5Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 2
```
___

I'm not yet sure what to do best with the `msg` of `rcrnShaders.esp`. The existing `dirty` info is outdated and my current implementation would be like this:
```yaml
  - name: 'rcrnShaders.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/1875' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Make sure you have bEnableFileSelection=1 in SkyrimPrefs.ini under [Launcher].'
          - lang: de
            text: 'Stellen Sie sicher, dass bEnableFileSelection=1 in SkyrimPrefs.ini unter [Launcher] angegeben ist.'
          - lang: ja
            text: 'ランチャーから必ずSkyrimPrefs.iniのbEnableFileSelectionを=1にセットしてください。'
          - lang: ru
            text: 'Убедитесь, что строка bEnableFileSelection=1 в SkyrimPrefs.ini находитсся в секции [Launcher].'
    dirty:
      # Skyrim\RCRN\Optionals\fpresets\classic
      - <<: *quickClean
        crc: 0x06679BAF
        util: '[TES5Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 26
        udr: 3
      # Skyrim\RCRN\Optionals\fpresets\classic\fast
      - <<: *quickClean
        crc: 0x35E6ED89
        util: '[TES5Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 26
        udr: 3
      # Skyrim\RCRN\Optionals\fpresets\classic\slow
      - <<: *quickClean
        crc: 0x60E3B96F
        util: '[TES5Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 26
        udr: 3
      # Skyrim\RCRN\Optionals\fpresets\legacy
      - <<: *quickClean
        crc: 0xB012D842
        util: '[TES5Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 29
        udr: 3
      # Skyrim\RCRN\Optionals\fpresets\legacy\fast
      - <<: *quickClean
        crc: 0xD6A9DCF7
        util: '[TES5Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 29
        udr: 3
      # Skyrim\RCRN\Optionals\fpresets\legacy\slow
      - <<: *quickClean
        crc: 0xDA725D74
        util: '[TES5Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 29
        udr: 3
      # Skyrim\RCRN\Optionals\fpresets\pure
      - <<: *quickClean
        crc: 0xC1737A79
        util: '[TES5Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 26
        udr: 3
      # Skyrim\RCRN\Optionals\fpresets\pure\fast
      - <<: *quickClean
        crc: 0x3D16E922
        util: '[TES5Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 26
        udr: 3
      # Skyrim\RCRN\Optionals\fpresets\pure\slow
      - <<: *quickClean
        crc: 0xF3813F94
        util: '[TES5Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrim/mods/25859)'
        itm: 26
        udr: 3
```
All the different versions of `RCRNdgdb.esp`, `RCRNdawnguard.esp`, `RCRNdragonborn.esp` and `RCRNvolumetric.esp` are clean. So the entry for `RCRNvolumetric.esp` that only consists out of the outdated dirty info can likely be removed.
___

The `RCRN (Classic|Legacy|Pure) - Hybrid Shaders\.esp` plugins are also from [RCRN](https://www.nexusmods.com/skyrim/mods/1875), though from the old version 2.1, and they aren't present in the latest version. As such, removing this entry would be best.
___

Also, if someone wants to see old instructions on how this mod possibly could be installed via MO, enter this link in the [Wayback Machine](https://archive.org/web/) and select a version from March 2016:

`http://www.rcrncommunity.com/forums/technical-support/guide-to-install-rcrn-ae-with-mod-organizer/`
